import assert from 'node:assert/strict';
import { test } from 'node:test';
import { sharedHistoryLock } from './live-history-lock-fixture';
import { createAdmissionClient } from '../gate-service/src/client';
import { LiveController, type GateClient } from '../src/live/controller';
import { type BrowserSession, type Custody, type PublicReceipt, type Sdk, type WalletApi } from '../src/live/model';
const eventId='11'.repeat(32),contract='22'.repeat(32),issuer='33'.repeat(32),commitment='44'.repeat(32);
const manifest={network:'preview',contractAddress:contract,eventId,issuerCommitment:issuer};
function publicReceipt(action:PublicReceipt['action']='issue'):PublicReceipt{return {schema:'midnight-event-pass-receipt-v1',network:'preview',action,contractAddress:contract,txId:'aa'.repeat(33),identifiers:['aa'.repeat(33)],txHash:'bb'.repeat(32),blockHash:'cc'.repeat(32),blockHeight:9,blockTimestamp:1,transactionStatus:'SucceedEntirely',stateCheck:'verified-at-finalized-block',eventId,...(action==='deploy'?{}:{commitment}),publicState:{eventId,issuerCommitment:issuer,issuedCount:'1',redeemedCount:action==='redeem'?'1':'0',revokedCount:'0',passStatus:action==='redeem'?'USED':'ACTIVE'}};}
function fixture() {
 const data=new Map<string,string>(), journal=new Map<string,{state:string;receipt?:PublicReceipt;requestId?:string;network?:string;action?:string;eventId?:string;issuerCommitment?:string;contractAddress?:string;commitment?:string;expiresAt?:number;txId?:string}>();let ids=0;let effects=0;let closes=0;let disconnected=false;let next:'success'|'unknown'|'rejected'='success';let joinState:unknown;let options:Parameters<Sdk['createBrowserSession']>[0]|undefined;
 const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v)}};
 const authorize=async(action:'issue'|'redeem'|'revoke'|'deploy',requestId:string)=>{
   if(!await options!.authorizeOperation({action,network:'preview',eventId,contractAddress:contract,commitment:action==='deploy'?undefined:commitment,usesPrivateProver:true,proofDestination:'owner synthetic fixture',persistsMaintenanceKey:action==='deploy',persistsPrivateState:true,paysDust:true}))throw Error('Owner approval was not granted');
   if(next==='rejected')throw Error('Synthetic rejection before journal');effects++;
   journal.set(requestId,{requestId,network:'preview',action,eventId,issuerCommitment:issuer,contractAddress:contract,...(action==='deploy'?{}:{commitment}),expiresAt:Date.now()+1000,state:next==='unknown'?'unknown':'verified',...(next==='success'?{txId:publicReceipt(action).txId,receipt:publicReceipt(action)}:{})});
   if(next==='unknown')throw Error('Synthetic submission interruption');return publicReceipt(action);
 };
 const session={scope:{network:'preview',ownerAccountId:'owner',eventId,role:'issuer'},configuration:{networkId:'preview',indexerUri:'https://synthetic.invalid/indexer',indexerWsUri:'wss://synthetic.invalid/indexer',substrateNodeUri:'https://synthetic.invalid/node'},
 adapter:{join:async(input:unknown)=>{joinState=input},issue:(id:string)=>authorize('issue',id),revoke:(id:string)=>authorize('revoke',id),redeem:(id:string)=>authorize('redeem',id),deploy:(input:{requestId:string})=>authorize('deploy',input.requestId)},
 close:()=>{closes++},checkConnection:async()=>{if(disconnected)throw Error('Synthetic disconnect')},readAttempt:async(id:string)=>journal.get(id)??null,reconcile:async(id:string)=>journal.get(id)?.receipt??null,
 } as unknown as BrowserSession;
 const sdk={createBrowserSession:async(input:Parameters<Sdk['createBrowserSession']>[0])=>{options=input;session.scope=input.scope;if(!await input.authorizeStorage({action:'open-owner-private-store',scope:input.scope,persistsEncryptedCapabilities:true,persistsEncryptedMaintenanceKeys:input.scope.role==='issuer',keyIsSuppliedByOwner:true}))throw Error('Synthetic storage declined');if(!await input.authorizeConnection({name:'synthetic wallet',rdns:'test.fixture',network:'preview'}))throw Error('Synthetic connection declined');if(!await input.authorizeWalletProver({action:'use-wallet-prover',network:'preview',proofDestination:'owner synthetic fixture',privatePreimagesLeavePage:true}))throw Error('Synthetic prover declined');return session},
 readChainStatus:async()=>({network:'preview',nodeVersion:'synthetic',finalizedBlockHash:'cc'.repeat(32),finalizedBlockHeight:9,checkedAt:'2026-10-05T00:00:00Z'}),createReadOnlyPublicProvider:()=>({}),readPublicState:async()=>publicReceipt().publicState,derivePassCommitment:()=>new Uint8Array(32).fill(0x44),
 } as unknown as Sdk;
 const controller=new LiveController({storage,publicHistoryLock:sharedHistoryLock(),loadSdk:async()=>sdk,requestId:()=>`request-${++ids}`,assets:()=> 'https://synthetic.invalid/assets/'});
 const c=(role:'issuer'|'bearer'='issuer'):Custody=>({role,ownerAccountId:'owner',eventId,encryptionKey:{} as CryptoKey,capability:new Uint8Array(32).fill(1),...(role==='issuer'?{maintenanceSigningKey:'66'.repeat(32)}:{})});
 async function reviewed<T>(work:()=>Promise<T>,answer=true){const unsubscribe=controller.consent.subscribe(()=>{if(controller.consent.getSnapshot())queueMicrotask(()=>controller.consent.respond(answer))});try{return await work()}finally{unsubscribe()}}
 async function ready(role:'issuer'|'bearer'='issuer'){await controller.load();controller.setCustody(c(role));await reviewed(()=>controller.connect({} as WalletApi,'owner synthetic fixture'));await controller.readNetwork();await reviewed(()=>controller.join(manifest));}
 return {controller,storage,journal,session,sdk,c,ready,reviewed,effects:()=>effects,closes:()=>closes,joinState:()=>joinState,setNext:(value:typeof next)=>{next=value},disconnectWallet:()=>{disconnected=true}};
}
test('loading/default live controller never connects wallet, provisions private authority or submits',async()=>{const f=fixture();await f.controller.load();assert.equal(f.effects(),0);assert.equal(f.controller.getSnapshot().connected,false);assert.equal(f.controller.getSnapshot().custodyReady,false);assert.equal(f.controller.getSnapshot().attempts.length,0)});
test('declined owner storage/connect setup stays disconnected with no provider effect',async()=>{const f=fixture();await f.controller.load();f.controller.setCustody(f.c());await f.reviewed(()=>f.controller.connect({} as WalletApi,'owner synthetic fixture'),false);assert.equal(f.controller.getSnapshot().connected,false);assert.equal(f.effects(),0)});
test('issuer join receives issuer capability only; real receipt fields are distinct from request ID',async()=>{const f=fixture();await f.ready();const state=f.joinState() as {initialPrivateState:Record<string,unknown>};assert.equal('issuerSecret' in state.initialPrivateState,true);assert.equal('bearerSecret' in state.initialPrivateState,false);await f.reviewed(()=>f.controller.issue(commitment));const attempt=f.controller.getSnapshot().attempts[0];assert.equal(attempt.status,'verified');assert.equal(attempt.receipt?.stateCheck,'verified-at-finalized-block');assert.equal(attempt.requestId,'request-1');assert.equal(attempt.receipt?.txId.length,66);assert.notEqual(attempt.requestId,attempt.receipt?.txId)});
test('unknown submission preserves public request and prevents duplicate/new submission until read-only reconciliation',async()=>{const f=fixture();await f.ready();f.setNext('unknown');await f.reviewed(()=>f.controller.issue(commitment));assert.equal(f.controller.getSnapshot().attempts[0].status,'unknown');assert.equal(f.effects(),1);await f.controller.issue(commitment);assert.equal(f.effects(),1);await f.controller.reconcile('request-1');assert.equal(f.controller.getSnapshot().attempts[0].status,'unknown');f.journal.set('request-1',{requestId:'request-1',network:'preview',action:'issue',eventId,issuerCommitment:issuer,contractAddress:contract,commitment,expiresAt:Date.now()+1000,state:'verified',txId:publicReceipt().txId,receipt:publicReceipt()});await f.controller.reconcile('request-1');assert.equal(f.controller.getSnapshot().attempts[0].status,'verified');assert.equal(f.effects(),1)});
test('owner decline before submission records rejection without provider side effect',async()=>{const f=fixture();await f.ready();await f.reviewed(()=>f.controller.issue(commitment),false);assert.equal(f.effects(),0);assert.equal(f.controller.getSnapshot().attempts[0].status,'rejected');assert.equal(f.controller.getSnapshot().attempts[0].receipt,undefined)});
test('scope and role checks prevent issuer redemption and bearer issuance',async()=>{const issuerFixture=fixture();await issuerFixture.ready();await issuerFixture.controller.redeem('gate-request',commitment);assert.equal(issuerFixture.effects(),0);const bearerFixture=fixture();await bearerFixture.ready('bearer');await bearerFixture.controller.issue(commitment);assert.equal(bearerFixture.effects(),0);const state=bearerFixture.joinState() as {initialPrivateState:Record<string,unknown>};assert.equal('bearerSecret' in state.initialPrivateState,true);assert.equal('issuerSecret' in state.initialPrivateState,false)});
test('wallet disconnect/account guard locks session and discards in-memory capability, keeps pending request',async()=>{const f=fixture();await f.ready();f.setNext('unknown');await f.reviewed(()=>f.controller.issue(commitment));f.disconnectWallet();await f.controller.checkConnection();const view=f.controller.getSnapshot();assert.equal(view.connected,false);assert.equal(view.custodyReady,false);assert.equal(view.credential,undefined);assert.equal(view.attempts[0].requestId,'request-1');assert.equal(view.attempts[0].status,'unknown');assert.ok(f.closes()>0)});
test('gate opening timeout persists original public request and blocks fresh open',async()=>{const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));let opens=0;const client={health:async()=>({schema:'guestlist-gate-health-v1',policy:'active-before-redemption-v1',storage:'durable-shared',events:[manifest]}),close:()=>{},openRedemption:async()=>{opens++;throw Error('Synthetic lost response')},claimRedemption:async()=>{throw Error('Not called')}} as GateClient;await f.controller.setGate(client);await f.controller.openGate(commitment);const context=f.controller.getSnapshot().gateContext;assert.equal(context?.status,'unknown');assert.equal(context?.requestId,'request-1');await f.controller.openGate(commitment);assert.equal(opens,1)});
test('gate never admits mismatched/forged success and status reads remain closed',async()=>{const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));const client={health:async()=>({schema:'guestlist-gate-health-v1',policy:'active-before-redemption-v1',storage:'durable-shared',events:[manifest]}),close:()=>{},openRedemption:async(input:Record<string,unknown>)=>({admit:false,code:'opened',attempt:{...input,baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:8,expiresAt:100}}),claimRedemption:async(input:{requestId:string})=>({admit:true,code:'admitted',requestId:input.requestId,receipt:{...publicReceipt('redeem'),eventId:'99'.repeat(32)}}),readRedemption:async()=>({admit:false,code:'claimed',attempt:{status:'claimed'},receipt:publicReceipt('redeem')})} as unknown as GateClient;await f.controller.setGate(client);await f.controller.openGate(commitment);await f.controller.claimGate('request-1','aa'.repeat(33));assert.notEqual(f.controller.getSnapshot().admission?.admit,true);await f.controller.readGate('request-1');assert.equal(f.controller.getSnapshot().admission?.admit,false)});
test('matching durable first claim alone grants admission; replay response stays closed',async()=>{const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));let claimed=false;const client={health:async()=>({schema:'guestlist-gate-health-v1',policy:'active-before-redemption-v1',storage:'durable-shared',events:[manifest]}),close:()=>{},openRedemption:async(input:Record<string,unknown>)=>({admit:false,code:'opened',attempt:{...input,baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:8,expiresAt:100}}),claimRedemption:async(input:{requestId:string})=>{const admit=!claimed;claimed=true;return{admit,code:admit?'admitted':'already-claimed',requestId:input.requestId,receipt:publicReceipt('redeem')}}} as unknown as GateClient;await f.controller.setGate(client);await f.controller.openGate(commitment);await f.controller.claimGate('request-1','aa'.repeat(33));assert.equal(f.controller.getSnapshot().admission?.admit,true);await f.controller.claimGate('request-1','aa'.repeat(33));assert.equal(f.controller.getSnapshot().admission?.admit,false);assert.equal(f.effects(),0)});
function deferred<T>() { let resolve!: (value:T)=>void; const promise=new Promise<T>(r=>{resolve=r});return{promise,resolve}; }
function syntheticGate(overrides:Partial<GateClient>={}):GateClient {
 return {health:async()=>({schema:'guestlist-gate-health-v1',policy:'active-before-redemption-v1',storage:'durable-shared',events:[manifest]}),close:()=>{},openRedemption:async(input)=>({admit:false,code:'opened',attempt:{...input,baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:8,expiresAt:100}}),claimRedemption:async(input)=>({admit:true,code:'admitted',requestId:input.requestId,receipt:publicReceipt('redeem')}),...overrides};
}
test('lock during deferred successful gate claim discards late admission and preserves unknown request',async()=>{
 const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));const response=deferred<Awaited<ReturnType<GateClient['claimRedemption']>>>();let closes=0;
 await f.controller.setGate(syntheticGate({close:()=>{closes++},claimRedemption:()=>response.promise}));await f.controller.openGate(commitment);
 const pending=f.controller.claimGate('request-1','aa'.repeat(33));await Promise.resolve();f.controller.disconnect();response.resolve({admit:true,code:'admitted',requestId:'request-1',receipt:publicReceipt('redeem')});await pending;
 const view=f.controller.getSnapshot();assert.equal(view.connected,false);assert.equal(view.custodyReady,false);assert.notEqual(view.admission?.admit,true);assert.equal(view.gateContext?.status,'unknown');assert.equal(view.gateContext?.requestId,'request-1');assert.equal(view.gateContext?.txId,'aa'.repeat(33));assert.equal(view.message.startsWith('Locked.'),true);assert.ok(closes>0);
});
test('lock during gate health prevents late credential attachment',async()=>{
 const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));const health=deferred<Awaited<ReturnType<GateClient['health']>>>();let closes=0;let opens=0;
 const pending=f.controller.setGate(syntheticGate({health:()=>health.promise,close:()=>{closes++},openRedemption:async()=>{opens++;throw Error('Not attached')}}));await Promise.resolve();f.controller.disconnect();health.resolve({schema:'guestlist-gate-health-v1',policy:'active-before-redemption-v1',storage:'durable-shared',events:[manifest]});await pending;await f.controller.openGate(commitment);assert.equal(opens,0);assert.ok(closes>0);assert.equal(f.controller.getSnapshot().custodyReady,false);
});
test('lock during gate open preserves unknown context without late ready/admission message',async()=>{
 const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));const opened=deferred<Awaited<ReturnType<GateClient['openRedemption']>>>();await f.controller.setGate(syntheticGate({openRedemption:()=>opened.promise}));const pending=f.controller.openGate(commitment);await Promise.resolve();f.controller.disconnect();opened.resolve({admit:false,code:'opened',attempt:{requestId:'request-1',...manifest,network:'preview',commitment,baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:8,expiresAt:100}});await pending;assert.equal(f.controller.getSnapshot().gateContext?.status,'unknown');assert.equal(f.controller.getSnapshot().admission,undefined);assert.equal(f.controller.getSnapshot().message.startsWith('Locked.'),true);
});
test('lock cancels pending owner event review without restoring trusted event',async()=>{
 const f=fixture();await f.controller.load();const review=f.controller.reviewEvent(manifest);await Promise.resolve();assert.ok(f.controller.consent.getSnapshot());f.controller.disconnect();await review;assert.equal(f.controller.getSnapshot().event,undefined);assert.equal(f.controller.getSnapshot().joined,false);
});
test('malformed truthy admission wire values are rejected and never rendered as a grant',async()=>{
 for(const bad of ['false','true',1,{},null,undefined]){
  const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));
  await f.controller.setGate(syntheticGate({claimRedemption:async(input)=>({admit:bad,code:'admitted',requestId:input.requestId,receipt:publicReceipt('redeem')}) as unknown as Awaited<ReturnType<GateClient['claimRedemption']>>}));
  await f.controller.openGate(commitment);await f.controller.claimGate('request-1','aa'.repeat(33));assert.notEqual(f.controller.getSnapshot().admission?.admit,true);assert.equal(f.controller.getSnapshot().gateContext?.status,'unknown');
 }
});
test('starting a different gate request removes a previous admission grant immediately',async()=>{
 const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));let calls=0;const response=deferred<Awaited<ReturnType<GateClient['openRedemption']>>>();
 await f.controller.setGate(syntheticGate({openRedemption:async(input)=>{calls++;return calls===1?{admit:false,code:'opened',attempt:{...input,baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:8,expiresAt:100}}:response.promise}}));
 await f.controller.openGate(commitment);await f.controller.claimGate('request-1','aa'.repeat(33));assert.equal(f.controller.getSnapshot().admission?.admit,true);
 const pending=f.controller.openGate('77'.repeat(32));await Promise.resolve();assert.notEqual(f.controller.getSnapshot().admission?.admit,true);f.controller.disconnect();response.resolve({admit:false,code:'opened',attempt:{requestId:'request-2',...manifest,network:'preview',commitment:'77'.repeat(32),baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:10,expiresAt:100}});await pending;
});
test('lock during delayed join never restores joined role or custody',async()=>{
 const f=fixture();await f.ready();const joined=deferred<void>();let began!:()=>void;const begun=new Promise<void>(r=>{began=r});f.session.adapter.join=async()=>{began();return joined.promise};
 const pending=f.reviewed(()=>f.controller.join(manifest));await begun;f.controller.disconnect();joined.resolve();await pending;assert.equal(f.controller.getSnapshot().joined,false);assert.equal(f.controller.getSnapshot().custodyReady,false);assert.equal(f.controller.getSnapshot().connected,false);
});
test('lock during finalized node read cannot restore chain readiness',async()=>{
 const f=fixture();await f.ready();const chain=deferred<Awaited<ReturnType<Sdk['readChainStatus']>>>();let began!:()=>void;const begun=new Promise<void>(r=>{began=r});f.sdk.readChainStatus=async()=>{began();return chain.promise};
 const pending=f.controller.readNetwork();await begun;f.controller.disconnect();chain.resolve({network:'preview',nodeVersion:'synthetic',finalizedBlockHash:'cc'.repeat(32),finalizedBlockHeight:12,checkedAt:'2026-10-05T00:00:00Z'});await pending;assert.equal(f.controller.getSnapshot().chain,undefined);assert.equal(f.controller.getSnapshot().connected,false);
});
test('lock during private presentation read cannot reveal a late credential',async()=>{
 const f=fixture();await f.ready('bearer');const state=deferred<Awaited<ReturnType<Sdk['readPublicState']>>>();let began!:()=>void;const begun=new Promise<void>(r=>{began=r});let encoded=0;
 f.sdk.readPublicState=async()=>{began();return state.promise};f.sdk.encodeLiveCredential=()=>{encoded++;return 'synthetic-private-fixture'};
 const pending=f.reviewed(()=>f.controller.present());await begun;f.controller.disconnect();state.resolve(publicReceipt().publicState);await pending;assert.equal(encoded,0);assert.equal(f.controller.getSnapshot().credential,undefined);assert.equal(f.controller.getSnapshot().custodyReady,false);
});
test('lock during late successful chain result preserves request as unknown until explicit read-only reconcile',async()=>{
 const f=fixture();await f.ready();const submitted=deferred<PublicReceipt>();let began!:()=>void;const begun=new Promise<void>(r=>{began=r});f.session.adapter.issue=async(id)=>{f.journal.set(id,{state:'unknown'});began();return submitted.promise};
 const pending=f.controller.issue(commitment);await begun;f.controller.disconnect();f.journal.set('request-1',{requestId:'request-1',network:'preview',action:'issue',eventId,issuerCommitment:issuer,contractAddress:contract,commitment,expiresAt:Date.now()+1000,state:'verified',txId:publicReceipt().txId,receipt:publicReceipt()});submitted.resolve(publicReceipt());await pending;
 assert.equal(f.controller.getSnapshot().attempts[0].status,'unknown');assert.equal(f.controller.getSnapshot().connected,false);assert.equal(f.controller.getSnapshot().state,undefined);
 await f.ready();await f.controller.reconcile('request-1');assert.equal(f.controller.getSnapshot().attempts[0].status,'verified');assert.equal(f.effects(),0);
});
test('actual strict browser admission client integrates through controller using public-only synthetic transport',async()=>{
 const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));const sent:Array<{path:string;body:Record<string,unknown>|undefined}>=[];let opened:Record<string,unknown>|undefined;
 const client=createAdmissionClient({serviceUrl:'https://synthetic.invalid/gate',gateId:'gate_fixture',apiSecret:'synthetic-only-gate-authority-xxxxxxxxxxxxxxxx',fetchImpl:async(input,init)=>{
  const path=new URL(String(input)).pathname;const body=init?.body?JSON.parse(String(init.body)) as Record<string,unknown>:undefined;sent.push({path,body});
  let result:unknown;
  if(path.endsWith('/health'))result={schema:'guestlist-gate-health-v1',policy:'active-before-redemption-v1',storage:'durable-shared',events:[manifest]};
  else if(path.endsWith('/open')){opened={...body,gateId:'gate_fixture',openedAt:1,expiresAt:100,baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:8,status:'open'};result={admit:false,code:'opened',attempt:opened};}
  else if(path.endsWith('/claim'))result={admit:true,code:'admitted',requestId:body!.requestId,receipt:publicReceipt('redeem')};
  else result={admit:false,code:'claimed',attempt:{...opened,status:'claimed',txId:'aa'.repeat(33)},receipt:publicReceipt('redeem')};
  return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});
 }});
 await f.controller.setGate(client);await f.controller.openGate(commitment);await f.controller.claimGate('request-1','aa'.repeat(33));assert.equal(f.controller.getSnapshot().admission?.admit,true);
 await f.controller.readGate('request-1');assert.equal(f.controller.getSnapshot().admission?.admit,false);
 for(const request of sent){assert.equal(JSON.stringify(request.body ?? {}).includes('bearerSecret'),false);assert.equal(JSON.stringify(request.body ?? {}).includes('issuerSecret'),false);assert.equal(JSON.stringify(request.body ?? {}).includes('apiSecret'),false)}
 f.controller.disconnect();assert.equal(f.effects(),0);
});
test('actual strict browser admission client rejects malformed grants before controller can render success',async()=>{
 const f=fixture();await f.controller.load();await f.reviewed(()=>f.controller.reviewEvent(manifest));
 const client=createAdmissionClient({serviceUrl:'https://synthetic.invalid/gate',gateId:'gate_fixture',apiSecret:'synthetic-only-gate-authority-xxxxxxxxxxxxxxxx',fetchImpl:async(input,init)=>{
  const path=new URL(String(input)).pathname;const body=init?.body?JSON.parse(String(init.body)) as Record<string,unknown>:undefined;
  const result=path.endsWith('/health')?{schema:'guestlist-gate-health-v1',policy:'active-before-redemption-v1',storage:'durable-shared',events:[manifest]}:path.endsWith('/open')?{admit:false,code:'opened',attempt:{...body,gateId:'gate_fixture',openedAt:1,expiresAt:100,baselineBlockHash:'cc'.repeat(32),baselineBlockHeight:8,status:'open'}}:{admit:'false',code:'admitted',requestId:'request-1',receipt:publicReceipt('redeem')};
  return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});
 }});
 await f.controller.setGate(client);await f.controller.openGate(commitment);await f.controller.claimGate('request-1','aa'.repeat(33));assert.notEqual(f.controller.getSnapshot().admission?.admit,true);assert.equal(f.controller.getSnapshot().gateContext?.status,'unknown');f.controller.disconnect();
});
