import {test,expect,type Page} from '@playwright/test';
const event={network:'preview',contractAddress:'11'.repeat(32),eventId:'22'.repeat(32),issuerCommitment:'33'.repeat(32)};
async function fresh(page:Page,hash='#preview') {await page.goto('/');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.goto('/'+hash);await expect(page.getByRole('heading',{name:'Your event. Your role.'})).toBeVisible()}
test('Preview begins with distinct roles and no private, wallet or gate form',async({page})=>{await fresh(page);await expect(page.getByRole('button',{name:/Organise an event/})).toBeVisible();await expect(page.getByRole('button',{name:/My pass/})).toBeVisible();await expect(page.getByRole('button',{name:/Run the door/})).toBeVisible();await expect(page.locator('input[type=password],input[type=file]')).toHaveCount(0);await expect(page.getByRole('navigation',{name:'Live pass workflow'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
test('gate journey contains no issuer/bearer or wallet setup',async({page})=>{await fresh(page);await page.getByRole('button',{name:/Run the door/}).click();await expect(page.getByRole('heading',{name:'Open your event invitation'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Gate staff progress'})).toBeVisible();await expect(page.getByLabel('Device password',{exact:true})).toHaveCount(0);await expect(page.getByLabel('Selected live wallet')).toHaveCount(0);await expect(page.getByLabel('Choose owner private recovery file')).toHaveCount(0);await expect(page.getByRole('button',{name:'Create a separate event'})).toHaveCount(0)});
test('public invitation selects guest review without trusting or connecting',async({page})=>{await page.goto('/');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.goto('/#event='+encodeURIComponent(JSON.stringify(event)));await expect(page.getByRole('heading',{name:'Continue with this event'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Guest progress'})).toBeVisible();const stored=await page.evaluate(()=>Object.keys(localStorage));expect(stored).not.toContain('guestlist.midnight-preview.trusted-event.v1');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('input[type=password]')).toHaveCount(0);await expect(page.getByText('Review needed',{exact:true})).toBeVisible()});
test('malformed or secret-bearing public event input fails closed',async({page})=>{await fresh(page);await page.getByRole('button',{name:/My pass/}).click();await page.getByText('Paste public code instead',{exact:true}).click();await page.getByLabel('event invitation',{exact:true}).fill(JSON.stringify({...event,bearerSecret:'not-public'}));await page.getByRole('button',{name:'Read public code',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'not a valid public Preview event invitation'})).toBeVisible();await expect(page.getByRole('button',{name:'Continue with this event'})).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('guestlist.midnight-preview.trusted-event.v1'))).toBeNull()});
test('role and route survive reload while custody remains locked',async({page})=>{await fresh(page);await page.getByRole('button',{name:/Organise an event/}).click();await page.reload();await expect(page.getByRole('heading',{name:'Organise your event'})).toBeVisible();await expect(page.getByRole('heading',{name:'Open your event invitation'})).toBeVisible();await expect(page.getByRole('button',{name:'Lock access'})).toHaveCount(0);await page.getByRole('button',{name:'Change role',exact:true}).click();await expect(page.getByRole('heading',{name:'Your event. Your role.'})).toBeVisible()});
test('public guest UI has no private QR or credential clipboard action',async({page})=>{await fresh(page);await page.getByRole('button',{name:/My pass/}).click();await expect(page.getByRole('button',{name:/private QR|Copy my private credential/})).toHaveCount(0);await expect(page.getByRole('img',{name:/private.*QR/i})).toHaveCount(0)});
for(const width of [320,390])test(`role and event layouts remain contained at ${width}px with 200% text`,async({page})=>{await page.setViewportSize({width,height:844});await fresh(page);await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:/My pass/}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole('heading',{name:'Open your event invitation'})).toBeVisible()});
