import { useEffect, useId, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Activity as ActivityIcon, AlertTriangle, CalendarDays, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, Copy, Fingerprint, Hash, LoaderCircle, LockKeyhole, MapPin, MoreHorizontal, Plus, QrCode, RotateCcw, Search, ShieldCheck, ShieldOff, Ticket, Users, WalletCards, X, XCircle, Clock3, Cable } from 'lucide-react';
import QRCode from 'qrcode';
import { EVENT, encodeCredential, newSecret, passNumber, statusOf, PassError, type Pass, type PassStatus, type Receipt, type Activity } from './domain';
import type { DemoService } from './demo-service';
type View='issue'|'wallet'|'checkin'|'passes'|'activity'|'network';
function route():View {const hash=location.hash.slice(1);if(hash==='overview'||!hash)return 'issue';if(hash==='guests')return 'passes';return ['issue','wallet','checkin','passes','activity','network'].includes(hash)?hash as View:'issue'}
const statusText: Record<PassStatus,string> = { ready:'Ready to enter', used:'Checked in', revoked:'Revoked', expired:'Expired' };
function Status({ status }: { status: PassStatus }) { const Icon = status === 'used' ? CheckCheck : status === 'revoked' ? ShieldOff : status === 'expired' ? Clock3 : Ticket; return <span className={`status status-${status}`}><Icon size={13}/>{statusText[status]}</span>; }
function timeLabel(at: string) { return new Intl.DateTimeFormat('en-GB',{ hour:'2-digit',minute:'2-digit', timeZone:'UTC' }).format(new Date(at)); }
function initials(label: string) { return label.split(' ').map(word=>word[0]).slice(0,2).join('').toUpperCase(); }
function Qr({ value, size=230 }: { value:string;size?:number }) { const [url,setUrl]=useState(''); useEffect(()=>{ let alive=true; QRCode.toDataURL(value,{ width:size, margin:4, errorCorrectionLevel:'M', color:{ dark:'#1d1d1f',light:'#ffffff' } }).then(result=>{if(alive)setUrl(result)}); return ()=>{alive=false}; },[value,size]); return url ? <img className="real-qr" src={url} width={size} height={size} alt="Bearer QR for this synthetic event pass"/> : <div className="qr-loading" style={{width:size,height:size}}><LoaderCircle className="spin"/></div>; }
function Modal({ title, subtitle, onClose, children, wide=false }: {title:string;subtitle?:string;onClose:()=>void;children:ReactNode;wide?:boolean}) { const ref=useRef<HTMLDialogElement>(null); const id=useId(); useEffect(()=>{const dialog=ref.current;const trigger=document.activeElement instanceof HTMLElement?document.activeElement:null;dialog?.showModal();dialog?.querySelector<HTMLInputElement>('input:not([type=radio]), textarea')?.focus();return()=>{dialog?.close();queueMicrotask(()=>{const active=document.activeElement;const topModal=Array.from(document.querySelectorAll('dialog[open]')).at(-1);if(trigger?.isConnected&&(!topModal||topModal.contains(trigger))&&(!active||active===document.body||!active.isConnected||dialog?.contains(active)))trigger.focus({preventScroll:true})})};},[]); return <dialog ref={ref} className={`dialog ${wide?'dialog-wide':''}`} aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog-head"><div><h2 id={id}>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>; }

function PassTable({passes,onView}:{passes:Pass[];onView:(pass:Pass)=>void}) {return <div className="table-wrap"><table><thead><tr><th>Guest</th><th>Pass</th><th>Status</th><th><span className="sr-only">View pass</span></th></tr></thead><tbody>{passes.map((pass,i)=><tr key={pass.id}><td><button className="guest-cell" onClick={()=>onView(pass)}><span className={`guest-avatar avatar-${i%5}`}>{initials(pass.label)}</span><span><strong>{pass.label}</strong><small>{pass.type} pass</small></span></button></td><td className="mono pass-cell">{passNumber(pass)}</td><td><Status status={statusOf(pass)}/></td><td><button className="icon-button table-action" aria-label={`View pass for ${pass.label}`} onClick={()=>onView(pass)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table></div>}
function GuestList({passes,onView,onIssue}:{passes:Pass[];onView:(pass:Pass)=>void;onIssue:()=>void}) { const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'all'|PassStatus>('all'); const filtered=passes.filter(p=>(filter==='all'||statusOf(p)===filter)&&(p.label.toLowerCase().includes(query.toLowerCase())||passNumber(p).toLowerCase().includes(query.toLowerCase())));return <section className="panel guest-panel"><div className="list-toolbar"><div className="filter-tabs" aria-label="Filter passes">{(['all','ready','used','revoked','expired'] as const).map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'filter-active':''} aria-pressed={filter===f}>{f==='all'?'All guests':f==='ready'?'Ready':f==='used'?'Checked in':f==='revoked'?'Revoked':'Expired'}<span>{passes.filter(p=>f==='all'||statusOf(p)===f).length}</span></button>)}</div><label className="search-field"><Search size={17}/><span className="sr-only">Search guests</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a guest or pass…"/></label></div>{filtered.length?<PassTable passes={filtered} onView={onView}/>:<div className="empty-state"><Search size={32}/><h2>{query?'No guests found':'Nobody here yet'}</h2><p>{query?'Try another name or pass number.':'Issue a pass to add someone to this group.'}</p><button className="button secondary" onClick={()=>{if(query||filter!=='all'){setQuery('');setFilter('all')}else onIssue()}}>{query||filter!=='all'?'Clear filters':'Issue a pass'}</button></div>}<div className="table-footer"><span>{filtered.length} of {passes.length} guests</span><span>Names are synthetic and offchain<LockKeyhole size={13}/></span></div></section>}
function ActivityList({activity,expanded=false}:{activity:Activity[];expanded?:boolean}) {return <div className={`activity-list ${expanded?'activity-expanded':''}`}>{activity.length?activity.map(item=>{const Icon=item.type==='issue'?Plus:item.type==='redeem'?CheckCheck:ShieldOff;return <div className="activity-item" key={item.id}><div className={`activity-icon activity-${item.type}`}><Icon size={17}/></div><div className="activity-copy"><strong>{item.type==='issue'?'Pass issued':item.type==='redeem'?'Guest checked in':'Pass revoked'}</strong><p>{item.label}</p>{expanded&&<span className="mono activity-receipt">{item.operationId}</span>}</div><time dateTime={item.at}>{timeLabel(item.at)}<small>UTC</small></time></div>}):<div className="empty-state"><ActivityIcon/><h3>No activity yet</h3><p>Issue or check in a pass to begin.</p></div>}</div>}
async function copy(value:string,notify:(text:string,error?:boolean)=>void) {try{await navigator.clipboard.writeText(value);notify('Credential copied. Treat it like a ticket.')}catch{notify('Copy unavailable here. Select the credential in the details below.',true)}}
function PassDialog({pass,onClose,onRevoke,onWallet,notify}:{pass:Pass;onClose:()=>void;onRevoke:(pass:Pass)=>void;onWallet:(pass:Pass)=>void;notify:(text:string,error?:boolean)=>void}) {const status=statusOf(pass);const [showSecret,setShowSecret]=useState(false);return <Modal title={pass.label} subtitle={`${passNumber(pass)} · ${pass.type} pass · Synthetic guest`} onClose={onClose}><div className="dialog-body pass-details"><div className="pass-summary"><div className="guest-avatar avatar-0">{initials(pass.label)}</div><Status status={status}/></div><dl><div><dt>Event</dt><dd>{EVENT.name}</dd></div><div><dt>Admission window</dt><dd>Until 24 Oct 2026, 00:00 UTC</dd></div><div><dt>Demo commitment</dt><dd className="mono break-word">{pass.commitment}</dd></div><div><dt>Verification</dt><dd>Local state only · no chain receipt</dd></div></dl><div className="private-detail"><LockKeyhole size={16}/><span>The guest label and bearer secret are offchain. This preview keeps both in local browser storage.</span></div><button className="text-button" onClick={()=>setShowSecret(!showSecret)}>{showSecret?'Hide':'Show'} bearer credential<ChevronDown size={14}/></button>{showSecret&&<textarea className="credential-value" readOnly value={encodeCredential(pass)} aria-label="Bearer credential"/>}</div><div className="dialog-actions pass-dialog-actions">{status==='ready'&&<button className="text-button danger-text" onClick={()=>onRevoke(pass)}><ShieldOff size={15}/>Revoke</button>}<button className="button secondary" onClick={()=>copy(encodeCredential(pass),notify)}><Copy size={16}/>Copy</button><button className="button primary" onClick={()=>onWallet(pass)}><WalletCards size={17}/>View pass</button></div></Modal>}
export function App({service,executionControls}:{service:DemoService;executionControls?:ReactNode}) {
 const [view,setView]=useState<View>(route);const [revision,setRevision]=useState(0);const [walletId,setWalletId]=useState(service.state.passes[0]?.id??'');const [issuedId,setIssuedId]=useState<string|null>(null);const [checkinSeed,setCheckinSeed]=useState<string|null>(null);
 const [detail,setDetail]=useState<Pass|null>(null);const [revoke,setRevoke]=useState<Pass|null>(null);const [more,setMore]=useState(false);const [reset,setReset]=useState(false);const [busy,setBusy]=useState(false);const [toast,setToast]=useState('');const [toastError,setToastError]=useState(false);
 const passes=service.state.passes;const selected=passes.find(p=>p.id===walletId)??passes[0];const issued=passes.find(p=>p.id===issuedId);
 useEffect(()=>service.subscribe(()=>setRevision(v=>v+1)),[service]);
 useEffect(()=>{const sync=()=>service.sync();window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[service]);
 useEffect(()=>{const hash=()=>{setView(route());setMore(false)};window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash)},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t)},[toast]);
 function go(next:View){setView(next);location.hash=next;setMore(false);window.scrollTo({top:0,behavior:'instant'})}
 const notify=(text:string,error=false)=>{setToast(text);setToastError(error)};
 async function confirmRevoke(){if(!revoke||busy)return;setBusy(true);try{await service.execute({type:'revoke',passId:revoke.id},'organiser');notify(`${passNumber(revoke)} revoked`);setRevoke(null);setDetail(null)}catch(e){notify(e instanceof Error?e.message:'Could not revoke this pass',true)}finally{setBusy(false)}}
 return <div className="product" data-revision={revision}>
  <a href="#main" className="skip-link" onClick={e=>{e.preventDefault();const main=document.getElementById('main');main?.focus({preventScroll:true});main?.scrollIntoView({block:'start',behavior:'instant'})}}>Skip to content</a>{executionControls}
  <header className="product-header"><button className="brand" aria-label="Guestlist organiser" onClick={()=>go('issue')}><Ticket size={24}/><span>guestlist</span></button><span className="execution-label">Local preview · synthetic data</span><button className="icon-button" aria-label="More options" onClick={()=>setMore(true)}><MoreHorizontal size={22}/></button></header>
  <div className="event-context"><div><h1>{EVENT.name}</h1><p><CalendarDays size={14}/><span>23 October 2026 · 18:00 UTC</span><span className="context-separator">·</span><MapPin size={14}/><span>{EVENT.location}</span></p></div><button className="context-link" onClick={()=>go('network')}><Cable size={15}/>No chain connected</button></div>
  <nav className="workflow-nav" aria-label="Pass workflow">{([{id:'issue',label:'Issue pass',icon:Plus},{id:'wallet',label:'Present pass',icon:WalletCards},{id:'checkin',label:'Check-in',icon:QrCode}] as const).map(({id,label,icon:Icon},i)=><button key={id} aria-label={label} onClick={()=>{if(id==='checkin')setCheckinSeed(null);go(id)}} aria-current={view===id?'page':undefined} className={view===id?'workflow-active':''}><span className="step-index">{i+1}</span><Icon size={18}/><span>{label}</span></button>)}</nav>
  <main id="main" tabIndex={-1} className="workspace-main">
   {service.storageWarning&&<p className="inline-warning" role="status"><AlertTriangle size={18}/>{service.storageWarning}</p>}
   {view==='issue'&&<IssueWorkspace key={issuedId??'new'} service={service} issued={issued} onIssued={pass=>{setIssuedId(pass.id);setWalletId(pass.id);notify(`${passNumber(pass)} created`)}} onAnother={()=>{setIssuedId(null);requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('[aria-label="Guest label"]')?.focus())}} onPresent={()=>go('wallet')} onManage={()=>go('passes')} notify={notify} total={passes.length}/>}
   {view==='wallet'&&<AttendeeWorkspace pass={selected} passes={passes} onSelect={setWalletId} onDetails={setDetail} notify={notify} onCheck={()=>{setCheckinSeed(selected?.id??null);go('checkin')}}/>}
   {view==='checkin'&&<GateWorkspace key={checkinSeed??'empty'} passes={passes} service={service} prefillId={checkinSeed}/>}
   {view==='passes'&&<><div className="section-heading"><div><h2>Issued passes</h2><p>{passes.length} passes for this event</p></div><button className="button primary" onClick={()=>{setIssuedId(null);go('issue')}}><Plus size={17}/>New pass</button></div><GuestList passes={passes} onView={setDetail} onIssue={()=>go('issue')}/></>}
   {view==='activity'&&<><div className="section-heading"><div><h2>Pass activity</h2><p>Local operations, not chain transactions</p></div><button className="button secondary" onClick={()=>go('passes')}>Issued passes</button></div><section className="panel full-activity"><ActivityList activity={service.state.activity} expanded/></section></>}
   {view==='network'&&<ConnectionWorkspace/>}
  </main>
  <footer className="product-footer"><span>Fixed demo clock: 5 Oct 2026, 17:00 UTC</span><button onClick={()=>setReset(true)}>Reset demo</button></footer>
  {more&&<Modal title="Event tools" onClose={()=>setMore(false)}><div className="more-actions"><button onClick={()=>go('passes')}><Users size={20}/><span>Issued passes</span><span>{passes.length}</span><ChevronRight size={18}/></button><button onClick={()=>go('activity')}><ActivityIcon size={20}/><span>Pass activity</span><ChevronRight size={18}/></button><button onClick={()=>go('network')}><Cable size={20}/><span>Connection & verification</span><ChevronRight size={18}/></button><button onClick={()=>{setMore(false);setReset(true)}}><RotateCcw size={20}/><span>Reset local demo</span><ChevronRight size={18}/></button></div></Modal>}
  {detail&&<PassDialog pass={passes.find(p=>p.id===detail.id)??detail} onClose={()=>setDetail(null)} onRevoke={setRevoke} onWallet={pass=>{setWalletId(pass.id);setDetail(null);go('wallet')}} notify={notify}/>}
  {revoke&&<Modal title="Revoke this pass?" subtitle={`${passNumber(revoke)} · ${revoke.label}`} onClose={()=>{if(!busy)setRevoke(null)}}><div className="dialog-body"><p>It will no longer work at check-in. This credential cannot be restored after revocation.</p></div><div className="dialog-actions"><button className="button secondary" disabled={busy} onClick={()=>setRevoke(null)}>Keep pass</button><button className="button danger" disabled={busy} onClick={confirmRevoke}>{busy?<LoaderCircle size={17} className="spin"/>:<ShieldOff size={17}/>}Revoke pass</button></div></Modal>}
  {reset&&<Modal title="Reset the local demo?" onClose={()=>setReset(false)}><div className="dialog-body"><p>Replace local passes and check-ins with the original 18 synthetic guests.</p></div><div className="dialog-actions"><button className="button secondary" onClick={()=>setReset(false)}>Keep my preview</button><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);await service.reset();setWalletId(service.state.passes[0]?.id??'');setIssuedId(null);setCheckinSeed(null);setReset(false);setBusy(false);notify('Demo reset')}}><RotateCcw size={17}/>Reset demo</button></div></Modal>}
  {toast&&<div className={`toast ${toastError?'toast-error':''}`} role={toastError?'alert':'status'}>{toastError?<AlertTriangle size={18}/>:<Check size={18}/>}<span>{toast}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={17}/></button></div>}
 </div>
}
function IssueWorkspace({service,issued,onIssued,onAnother,onPresent,onManage,notify,total}:{service:DemoService;issued?:Pass;onIssued:(pass:Pass)=>void;onAnother:()=>void;onPresent:()=>void;onManage:()=>void;notify:(text:string,error?:boolean)=>void;total:number}){
 const [label,setLabel]=useState('');const [type,setType]=useState<'Guest'|'Host'>('Guest');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const lock=useRef(false);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current||issued)return;lock.current=true;setBusy(true);setError('');try{const receipt=await service.execute({type:'issue',label,passType:type,secret:newSecret()},'organiser');onIssued(service.state.passes.find(p=>p.id===receipt.passId)!)}catch(e){setError(e instanceof Error?e.message:'Could not create this pass');lock.current=false}finally{setBusy(false)}}
 return <div className="issue-layout"><section className="issue-form-panel"><div className="section-heading"><h2>Issue an event pass</h2><span className="role-label">Organiser</span></div><form onSubmit={submit}><fieldset disabled={busy||!!issued} className="issue-fields"><label className="form-field">Guest label<input aria-label="Guest label" required minLength={2} maxLength={48} value={issued?.label??label} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Morgan Harper"/><small>Use an invented name for the demo</small></label><fieldset className="pass-type-choice"><legend>Pass type</legend>{(['Guest','Host'] as const).map(t=><label key={t} className={(issued?.type??type)===t?'choice-selected':''}><input type="radio" name="pass-type" value={t} checked={(issued?.type??type)===t} onChange={()=>setType(t)}/><span><Ticket size={19}/><strong>{t}</strong></span>{(issued?.type??type)===t&&<Check size={17}/>}</label>)}</fieldset></fieldset>{error&&<p className="form-error" role="alert"><AlertTriangle size={17}/>{error}</p>}{issued?<div className="issue-created"><span><Check size={17}/>{passNumber(issued)} created</span><button type="button" className="button secondary" onClick={onAnother}>Create another pass</button></div>:<button className="button primary create-pass" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Plus size={18}/>} {busy?'Creating pass…':'Create pass'}</button>}</form><button className="manage-link" onClick={onManage}><Users size={17}/>Manage issued passes<span>{total}</span><ChevronRight size={17}/></button><details className="technical-note"><summary>What is stored?</summary><p>The label and credential stay in this browser. The demo records a commitment and status. A real Midnight contract publishes commitments and states, not names. Host is a presentation label and adds no privileges.</p></details></section><section className={`issue-output ${issued?'output-issued':''}`} aria-live="polite">{issued?<><div className="output-heading"><span>Pass created</span><span className="mono">{passNumber(issued)}</span></div><PassFace pass={issued} compact/><div className="output-actions"><button className="button primary" onClick={onPresent}><WalletCards size={18}/>Present this pass</button><button className="button secondary" onClick={()=>copy(encodeCredential(issued),notify)}><Copy size={17}/>Copy credential</button></div></>:<div className="unissued-pass"><Ticket size={38} strokeWidth={1.4}/><h3>Your pass will appear here</h3><p>Create a pass to generate its QR</p></div>}</section></div>
}
function PassFace({pass,compact=false}:{pass:Pass;compact?:boolean}){const status=statusOf(pass);return <div className={`ticket-card ticket-${status} ${compact?'ticket-compact':''}`}><div className="ticket-upper"><div className="ticket-top"><span className="ticket-wordmark"><Ticket size={18}/>guestlist</span><span>ADMIT ONE</span></div><h2>{EVENT.name}</h2><div className="ticket-date"><CalendarDays size={16}/><span>23 October 2026<strong>18:00–22:00 UTC</strong></span></div><div className="ticket-location"><MapPin size={15}/>{EVENT.location}</div></div><div className="ticket-lower"><div className="ticket-guest"><div><span>PASS HOLDER</span><strong>{pass.label}</strong></div><span className="ticket-class">{pass.type}</span></div><div className={`ticket-qr ${status!=='ready'?'qr-disabled':''}`}><Qr value={encodeCredential(pass)} size={compact?214:252}/>{status!=='ready'&&<div className="qr-state-cover">{status==='used'?<CheckCheck size={30}/>:status==='revoked'?<ShieldOff size={30}/>:<Clock3 size={30}/>}<strong>{status==='used'?'Already used':statusText[status]}</strong><span>Not valid for another entry</span></div>}</div><div className="ticket-id"><span className="mono">{passNumber(pass)}</span><Status status={status}/></div></div></div>}
function AttendeeWorkspace({pass,passes,onSelect,onDetails,onCheck,notify}:{pass?:Pass;passes:Pass[];onSelect:(id:string)=>void;onDetails:(pass:Pass)=>void;onCheck:()=>void;notify:(text:string,error?:boolean)=>void}){if(!pass)return <div className="empty-state"><Ticket size={32}/><h2>No pass issued</h2><p>Create a pass in the Issue pass view</p></div>;return <section className="attendee-workspace"><div className="attendee-heading"><h2>Present your pass</h2><p>Show the QR at check-in</p></div><PassFace pass={pass}/><p className="pass-instruction">One entry · Keep this QR private</p><div className="attendee-actions"><button className="button secondary" onClick={()=>onDetails(pass)}>Pass details</button><button className="button secondary" onClick={()=>copy(encodeCredential(pass),notify)}><Copy size={16}/>Copy credential</button></div><details className="demo-tools"><summary>Preview tools</summary><div><label className="form-field">Preview pass<select aria-label="Choose an attendee pass" value={pass.id} onChange={e=>onSelect(e.target.value)}>{passes.map(p=><option key={p.id} value={p.id}>{p.label} · {passNumber(p)}</option>)}</select></label><button className="button primary" onClick={onCheck}><QrCode size={17}/>Try check-in</button><details className="credential-details"><summary>Credential text</summary><textarea aria-label="Selected pass credential" readOnly value={encodeCredential(pass)}/></details></div></details></section>}
function GateWorkspace({passes,service,prefillId}:{passes:Pass[];service:DemoService;prefillId:string|null}){
 const initial=passes.find(p=>p.id===prefillId);const [credential,setCredential]=useState(initial?encodeCredential(initial):'');const [selection,setSelection]=useState(initial?.id??passes[0]?.id??'');const [busy,setBusy]=useState(false);const [result,setResult]=useState<{receipt?:Receipt;pass?:Pass;error?:string;code?:string}|null>(null);const lock=useRef(false);const resultRef=useRef<HTMLElement>(null);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setResult(null);try{const receipt=await service.execute({type:'redeem',credential:credential.trim()},'attendee');setResult({receipt,pass:service.state.passes.find(p=>p.id===receipt.passId)})}catch(e){setResult({error:e instanceof Error?e.message:'Could not check this pass',code:e instanceof PassError?e.code:'error'})}finally{setBusy(false);lock.current=false}}
 useEffect(()=>{if(result)resultRef.current?.focus()},[result]);
 const reason=result?.code==='used'?'Already used':result?.code==='revoked'?'Revoked':result?.code==='expired'?'Expired':result?.code==='wrong-event'?'Wrong event':'Invalid pass';
 return <div className="gate-layout"><section className="gate-input"><div className="section-heading"><h2>Check in a pass</h2><span className="role-label">Entry</span></div><form onSubmit={submit}><label className="form-field">Credential<textarea required aria-label="Credential to check in" placeholder="Paste a Guestlist demo credential" value={credential} onChange={e=>{setCredential(e.target.value);setResult(null)}} disabled={busy}/></label><button className="button primary checkin-submit" disabled={busy||!credential.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<ShieldCheck size={18}/>} {busy?'Checking pass…':'Check in'}</button></form><details className="demo-tools"><summary>Use a demo pass</summary><div className="demo-picker"><label htmlFor="demo-pass">Synthetic guest</label><div><select id="demo-pass" value={selection} onChange={e=>setSelection(e.target.value)} disabled={busy}>{passes.map(p=><option key={p.id} value={p.id}>{p.label} · {statusText[statusOf(p)]}</option>)}</select><button className="button secondary" disabled={busy} onClick={()=>{const p=passes.find(p=>p.id===selection);if(p){setCredential(encodeCredential(p));setResult(null)}}}>Use pass</button></div></div></details></section><section ref={resultRef} tabIndex={-1} className={`gate-result ${result?(result.error?'result-rejected':'result-success'):'result-waiting'}`} role={result?.error?'alert':'status'}>{busy?<><LoaderCircle size={33} className="spin"/><h2>Checking pass</h2></>:result?<><span className="result-symbol">{result.error?<XCircle size={36}/>:<CheckCheck size={36}/>}</span><span className="result-label">{result.error?'ENTRY REJECTED':'DEMO CHECK-IN'}</span><h2>{result.error?reason:'Admitted'}</h2>{result.pass?<><p className="result-guest">{result.pass.label}</p><span className="mono result-number">{passNumber(result.pass)}</span><Status status="used"/></>:<p>{result.error}</p>}<p className="result-state">{result.error?'No entry recorded':'Pass marked as used'}</p>{result.receipt&&<details className="receipt-details"><summary>Operation details</summary><p className="mono break-word">{result.receipt.operationId}</p><p>{timeLabel(result.receipt.at)} UTC · local state</p></details>}<button className="button secondary" onClick={()=>{setResult(null);setCredential('');requestAnimationFrame(()=>document.querySelector<HTMLTextAreaElement>('[aria-label="Credential to check in"]')?.focus())}}>Check another pass</button></>:<><QrCode size={30}/><h2>Waiting for a pass</h2><p>Paste a credential or choose a demo pass</p></>}</section></div>
}
function ConnectionWorkspace(){return <section className="connection-workspace"><div className="section-heading"><h2>Connection & verification</h2><span className="role-label">Not connected</span></div><div className="connection-row"><LayoutMode/><div><h3>Local preview</h3><p>Issue, redeem and revoke use browser state and synthetic credentials. The preview clock is fixed at 5 October 2026, 17:00 UTC, so this example remains replayable. No wallet is connected and no transactions are submitted.</p></div></div><div className="connection-row"><Fingerprint size={22}/><div><h3>Midnight contract</h3><p>Original Compact source compiled with 0.31.1/runtime 0.16.0. Its generated contract passes 19 runtime tests and 6 compiler checks. Genuine local issue, redeem and revoke proofs passed the official prover’s cryptographic self-check; its wrong-verifier control was rejected.</p><p>The ledger WASM’s separate proof check is structural. The original Preview deployment and finalized block were independently verified. Accepted network issue, redeem and revoke transactions and live gate admission remain unverified.</p></div></div><div className="connection-row"><Cable size={22}/><div><h3>Recorded deployment and next steps</h3><p>Owner custody and wallet/prover setup were used for the recorded Preview deployment. Completing the live pass lifecycle requires the owner’s existing private credentials, test DUST and local prover, with explicit reviews. This Local preview submits no transactions.</p></div></div><details className="technical-note"><summary>Public and private data</summary><p>Guest labels and issuer/bearer secrets remain offchain. Public event IDs, commitments, status and transaction metadata can be linked. A bearer QR reveals bearer authority to whoever scans or copies it. The synthetic scanner receives a demo credential; the implemented live gate flow exchanges public request, commitment and transaction identifiers. An approved prover may see private inputs. A copied credential can be used first.</p></details></section>}
function LayoutMode(){return <Ticket size={22}/>}
