import { useEffect, useRef, useState, useSyncExternalStore, type ChangeEvent, type ReactNode } from 'react';
import { AlertTriangle, ArrowLeft, ArrowRight, Cable, Check, ChevronRight, Copy, Download, KeyRound, LoaderCircle, LockKeyhole, Plus, QrCode, ShieldCheck, Ticket, Users, WalletCards, X } from 'lucide-react';
import { createAdmissionClient } from '../gate-service/src/client';
import { LiveController } from './live/controller';
import { CONSENT_REQUIREMENTS, type ConsentQueue } from './live/consent';
import { createRecoveryFile, importOwnerFile, forgetCustody, readOwnerRecoveryMetadata, resolveRecoveryScope, type RecoveryMetadata } from './live/custody';
import { DeviceVault, downloadEncryptedBackup, readEncryptedBackupMetadata, validateVaultPassword, vaultScopeKey } from './live/device-vault';
import { hexFromBytes, isUnresolved, publicHex32, type GateContext, type PublicAttempt, type Role, type TrustedEvent, type WalletApi } from './live/model';
import { buildEventLink, parseEventLink, parsePublicEventManifest, encodePassRequest, encodeCheckInRequest, parsePassRequest, parseCheckInRequest, encodeGateRequest, parseGateRequest, parsePreservedGateRequest, encodeRedemptionReceipt, parseRedemptionReceipt, type PublicGateRequest, type PublicGateRequestContext } from './live/handoffs';
import { PublicQr, PublicCodeInput } from './live/handoff-ui';
import { readJourney, saveJourney, type Journey, type JourneyRole, type JourneyStage } from './live/journey-state';
import './live/styles.css';

const roleNames = {organiser:'Organiser',guest:'Guest',gate:'Gate staff'};
const knownEvent = {network:'preview' as const,contractAddress:'856fb78cc68d912c92e1c1bf33afaced96cb35baa5d0973daaab93eaadca0c65',eventId:'d033b2269fb0a7716928e3fa6fe2c6ca30daed553147c3cabd49998d875632d9',issuerCommitment:'d8f045c7bdae2e34113d6abba5f27d6d3a9a0bfefd6c8aed5f72e55230a68b06'};
function publicManifest(event: TrustedEvent) {return {network:'preview' as const,contractAddress:event.contractAddress,eventId:event.eventId,issuerCommitment:event.issuerCommitment}}
function gatePublic(context:GateContext):PublicGateRequestContext {if(context.expiresAt===undefined||context.baselineBlockHash===undefined||context.baselineBlockHeight===undefined)throw new Error('No open verified gate request');return {...publicManifest({...context,trust:'owner-reviewed'}),commitment:context.commitment,requestId:context.requestId,expiresAt:context.expiresAt,baselineBlockHash:context.baselineBlockHash,baselineBlockHeight:context.baselineBlockHeight}}
function sameEvent(a:ReturnType<typeof publicManifest>,b:ReturnType<typeof publicManifest>){return a.network===b.network&&a.contractAddress===b.contractAddress&&a.eventId===b.eventId&&a.issuerCommitment===b.issuerCommitment}

/** Local demo and real Preview never share services, private state or receipts. */
export function GuestlistModes({demo}:{demo:(controls:ReactNode)=>ReactNode}) {
  const [journey,setJourney]=useState(()=>readJourney(localStorage,location.hash));
  useEffect(()=>{const sync=()=>setJourney(readJourney(localStorage,location.hash));window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
  function navigate(next:Journey){saveJourney(localStorage,next);setJourney(next);location.hash=next.mode==='demo'?'issue':`preview${next.role?`/${next.role}/${next.stage}`:''}`;window.scrollTo({top:0,behavior:'instant'})}
  const controls=<section className="mode-switch" aria-label="Execution mode"><span>Experience</span><div><button aria-pressed={journey.mode==='demo'} onClick={()=>navigate({mode:'demo',stage:'event'})}>Local demo</button><button aria-pressed={journey.mode==='preview'} onClick={()=>navigate({mode:'preview',role:journey.role,stage:'event'})}>Midnight Preview</button></div><p>{journey.mode==='demo'?'Try the complete journey. No wallet needed.':'Real test network · your own keys and approvals'}</p></section>;
  return journey.mode==='demo'?demo(controls):<LiveApp executionControls={controls} journey={journey} navigate={navigate}/>;
}
export function LiveApp({executionControls,journey:provided,navigate:providedNavigate}:{executionControls?:ReactNode;journey?:Journey;navigate?:(next:Journey)=>void}) {
  const [controller]=useState(()=>new LiveController());const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);
  const [localJourney,setLocalJourney]=useState<Journey>({mode:'preview',stage:'event'});const journey=provided??localJourney;const navigate=providedNavigate??setLocalJourney;
  const [notice,setNotice]=useState('');const role=journey.role;
  const previousRole=useRef(role);
  useEffect(()=>{void controller.load();return()=>controller.disconnect()},[controller]);
  useEffect(()=>{if(previousRole.current!==role){controller.disconnect();previousRole.current=role}},[role,controller]);
  useEffect(()=>{if(!view.connected)return;const timer=setInterval(()=>void controller.checkConnection(),5000);const focus=()=>void controller.checkConnection();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus)}},[controller,view.connected]);
  const go=(stage:JourneyStage)=>{if(controller.getSnapshot().busy)controller.disconnect();navigate({mode:'preview',role,stage})};
  async function copyPublic(value:string){try{await navigator.clipboard.writeText(value);setNotice('Public information copied')}catch{setNotice('Clipboard unavailable. Use the public QR or select the text.')}}
  const unresolved=view.attempts.filter(isUnresolved);
  const stage=journey.stage;
  const lockedStage = !view.event && !['event','new-event','requests'].includes(stage) && !(stage==='wallet'&&view.custodyReady&&view.role==='issuer') ? 'event' : stage;
  const actualStage = role!=='gate'&&!view.custodyReady&&['pass','door','wallet'].includes(lockedStage)?'access':lockedStage;
  function exitRole(){controller.disconnect();navigate({mode:'preview',stage:'event'})}
  function returnToFlow(){if(!view.event)go('event');else if(role==='gate')go(view.gateReady?'door':'access');else if(!view.custodyReady)go('access');else if(role==='organiser'&&!view.joined)go('wallet');else go('pass')}
  return <div className="product live-product"><a href="#live-main" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('live-main')?.focus();document.getElementById('live-main')?.scrollIntoView({block:'start'})}}>Skip to content</a>{executionControls}
    <header className="product-header"><button className="brand" aria-label="Guestlist Preview roles" onClick={exitRole}><Ticket size={24}/><span>guestlist</span></button><span className="execution-label live-mode-label">Midnight Preview · real network</span>{role&&<button className="text-button" onClick={exitRole}>Change role</button>}</header>
    <div className="event-context"><div><h1>{!role?'Your event. Your role.':role==='organiser'?'Organise your event':role==='guest'?'Your invitation, privately held':'A clear decision at the door'}</h1><p>{role?<><span className="role-label">{roleNames[role]}</span><span>{view.event?'Existing Preview event':'Choose a trusted event to begin'}</span></>:'Choose what you’re here to do. We’ll guide the next step.'}</p></div>{role&&(view.custodyReady||view.gateReady)&&<button className="context-link" onClick={()=>{controller.disconnect();go('access')}}><LockKeyhole size={15}/>Lock access</button>}</div>
    <main id="live-main" tabIndex={-1} className="workspace-main">
      {!role?<RolePicker choose={next=>navigate({mode:'preview',role:next,stage:'event'})}/>:<>
        <nav className="journey-progress" aria-label={`${roleNames[role]} progress`}>{(role==='organiser'?['Event','Unlock','Connect','Issue']:role==='guest'?['Event','Unlock','My pass','Check-in']:['Event','Connect gate','Check-in']).map((label,i)=>{const steps:JourneyStage[]=role==='gate'?['event','access','door']:role==='organiser'?['event','access','wallet','pass']:['event','access','pass','door'];return <span key={label} aria-current={actualStage===steps[i]?'step':undefined}><span>{i+1}</span>{label}</span>})}</nav>
        {view.error&&<p role="alert" className="form-error"><AlertTriangle size={18}/>{view.error}</p>}
        {unresolved.length>0&&actualStage!=='requests'&&<section className="pending-banner" role="status"><div><strong>{unresolved.length===1?'An earlier request needs a status check':'Earlier requests need a status check'}</strong><p>Keep the same event and access. No action will be submitted again automatically.</p></div><button className="button secondary" onClick={()=>go('requests')}>Check saved requests</button></section>}
        {!view.loaded&&<p role="status" className="inline-warning"><LoaderCircle className="spin" size={18}/>Loading the genuine Midnight SDK. No wallet or key setup has started.</p>}
        {actualStage==='event'&&<EventStep controller={controller} role={role} onContinue={()=>go('access')} onNew={()=>{controller.disconnect();go('new-event')}} copyPublic={copyPublic}/>}
        {actualStage==='new-event'&&role==='organiser'&&<CustodyStep key="new" controller={controller} role="issuer" newEvent onReady={()=>go('wallet')} onBack={()=>go('event')}/>}
        {actualStage==='access'&&(role==='gate'?<section className="journey-card live-panel"><StepTitle eyebrow="Gate access" title="Connect the door" text="Use the existing gate connection file provided by your organiser. No wallet or private pass is needed."/><GateSetup controller={controller}/>{view.gateReady&&<><p className="live-good"><Check size={18}/>Exact event and durable admission service checked</p><button className="button primary" onClick={()=>go('door')}>Start scanning<ArrowRight size={17}/></button></>}<Back onClick={()=>go('event')}/></section>:<CustodyStep key={`${role}-${view.event?.eventId}`} controller={controller} role={role==='organiser'?'issuer':'bearer'} onReady={()=>go(role==='organiser'?'wallet':'pass')} onBack={()=>go('event')}/>)}
        {actualStage==='wallet'&&<WalletStep controller={controller} onReady={()=>go(role==='guest'?'door':'pass')} onBack={()=>go(role==='guest'?'pass':'access')}/>}
        {actualStage==='pass'&&role==='organiser'&&(view.joined?<IssueStep controller={controller}/>:<WalletStep controller={controller} onReady={()=>go('pass')} onBack={()=>go('access')}/>)}
        {actualStage==='pass'&&role==='guest'&&<GuestPass controller={controller} onDoor={()=>go('door')}/>}
        {actualStage==='door'&&role==='guest'&&<GuestDoor controller={controller} onWallet={()=>go('wallet')} onBack={()=>go('pass')}/>}
        {actualStage==='door'&&role==='gate'&&(view.gateReady?<GateFlow controller={controller}/>:<section className="journey-card live-panel"><StepTitle eyebrow="Access locked" title="Reconnect your gate" text="Gate authority stays in memory. Reconnect before verifying an entry."/><button className="button primary" onClick={()=>go('access')}>Connect gate</button></section>)}
        {actualStage==='requests'&&<><Back onClick={returnToFlow}/><Requests controller={controller} copyPublic={copyPublic}/></>}
        {view.busy&&<p className="live-busy" role="status"><LoaderCircle className="spin" size={17}/>Waiting for your review or verified network evidence. You can lock to cancel further steps; an already submitted transaction still needs a status check.</p>}
        <details className="technical-note journey-details"><summary>Event details & recovery</summary>{view.event&&<EventDetails event={view.event}/>}<p>{view.message||'No network operation has started.'}</p><button className="text-button" onClick={()=>go('requests')}>Public requests & receipts</button><button className="text-button" onClick={()=>{controller.disconnect();go('event')}}>Review a different event</button></details>
      </>}
    </main><footer className="product-footer"><span>Preview prototype · real admission requires independent verification and the gate’s first durable claim</span><span>No live lifecycle acceptance claimed</span></footer><ConsentDialog queue={controller.consent}/>{notice&&<div className="toast" role="status"><Check size={18}/><span>{notice}</span><button className="icon-button" aria-label="Dismiss copy status" onClick={()=>setNotice('')}><X size={17}/></button></div>}
  </div>;
}
function RolePicker({choose}:{choose:(role:JourneyRole)=>void}){return <div className="role-picker">{[{role:'organiser' as const,Icon:Users,title:'Organise an event',text:'Resume your event and approve guest requests.',hint:'Existing event first'},{role:'guest' as const,Icon:Ticket,title:'My pass',text:'Keep your invitation on your device. Share only a public code.',hint:'No wallet needed to request a pass'},{role:'gate' as const,Icon:QrCode,title:'Run the door',text:'Scan, verify and admit each pass once.',hint:'No wallet or prover setup'}].map(({role,Icon,title,text,hint})=><button className="role-card" key={role} onClick={()=>choose(role)}><span className="role-card-icon"><Icon size={25}/></span><h2>{title}</h2><p>{text}</p><span className="role-card-hint">{hint}<ChevronRight size={18}/></span></button>)}</div>}
function StepTitle({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="step-title"><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}
function Back({onClick}:{onClick:()=>void}){return <button className="text-button journey-back" onClick={onClick}><ArrowLeft size={15}/>Back</button>}
function EventDetails({event}:{event:ReturnType<typeof publicManifest>}){return <dl className="event-identity">{[['Network','Midnight Preview'],['Contract',event.contractAddress],['Event',event.eventId],['Issuer',event.issuerCommitment]].map(([name,value])=><div key={name}><dt>{name}</dt><dd className="mono break-word">{value}</dd></div>)}</dl>}
function EventStep({controller,role,onContinue,onNew,copyPublic}:{controller:LiveController;role:JourneyRole;onContinue:()=>void;onNew:()=>void;copyPublic:(value:string)=>Promise<void>}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const [candidate,setCandidate]=useState<ReturnType<typeof publicManifest>|undefined>(()=>{try{return location.hash.startsWith('#event=')?parseEventLink(location.href):view.event&&publicManifest(view.event)}catch{return undefined}});const [error,setError]=useState('');
  function accept(text:string){try{const parsed=text.startsWith('https:')||text.startsWith('http:')?parseEventLink(text):parsePublicEventManifest(text);setCandidate(parsed);setError('')}catch{setError('This is not a valid public Preview event invitation. Ask the organiser for their event link or public manifest.')}}
  async function selected(e:ChangeEvent<HTMLInputElement>){const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(!file)return;if(file.size>8192){setError('Event manifest is too large');return}accept(await file.text())}
  async function proceed(){if(!candidate)return;if(!view.event||!sameEvent(candidate,publicManifest(view.event)))await controller.reviewEvent(candidate);const next=controller.getSnapshot();if(next.event&&sameEvent(candidate,publicManifest(next.event))&&!next.error){await controller.readPublicEvent();if(controller.getSnapshot().publicVerified)onContinue()}}
  return <section className="journey-card live-panel"><StepTitle eyebrow="01 · Trusted event" title={candidate?'Continue with this event':'Open your event invitation'} text="Use a link or public manifest from an organiser you trust. A guest’s pass code cannot choose the event for you."/>{candidate?<><div className="event-preview"><Ticket size={25}/><div><strong>Midnight Preview event</strong><p>{candidate.eventId.slice(0,12)}… · {candidate.contractAddress.slice(0,12)}…</p></div><span className="role-label">{view.event&&sameEvent(candidate,publicManifest(view.event))?'Saved event':'Review needed'}</span></div><details className="technical-note"><summary>Check the public identity</summary><EventDetails event={candidate}/><p>A matching chain record verifies the code, not the organiser’s real-world identity.</p></details><button className="button primary" disabled={view.busy||!view.loaded} onClick={()=>void proceed()}>Continue with this event<ArrowRight size={17}/></button><button className="text-button" disabled={view.busy} onClick={()=>{setCandidate(undefined);setError('')}}>Use another invitation</button>{view.event&&sameEvent(candidate,publicManifest(view.event))&&<details className="technical-note"><summary>Share public event invitation</summary><PublicQr value={buildEventLink(location.origin+'/',candidate)} label="Public event invitation QR"/><button className="button secondary" onClick={()=>void copyPublic(buildEventLink(location.origin+'/',candidate))}>Copy public event link</button></details>}</>:<><PublicCodeInput label="event invitation" disabled={view.busy} onCode={accept}/><label className="live-file-picker">Or choose a public event manifest<input type="file" accept="application/json,.json" aria-label="Choose public event manifest" onChange={selected}/></label><button className="button secondary" onClick={()=>{setCandidate(knownEvent);setError('')}}>Use recorded Guestlist Preview event</button><p className="live-small-note">The recorded deployment was independently verified on 5 October 2026. Current status is checked again; network issue, redeem and gate acceptance are still unverified.</p></>}{error&&<p role="alert" className="form-error">{error}</p>}{role==='organiser'&&<details className="technical-note"><summary>Start a separate new event</summary><p>This creates different authority and requires a new deployment. It cannot recover an existing issuer or an unresolved transaction.</p><button className="button secondary" disabled={view.busy||view.attempts.some(isUnresolved)} onClick={onNew}>Create a separate event</button></details>}</section>;
}
function CustodyStep({controller,role,newEvent=false,onReady,onBack}:{controller:LiveController;role:Role;newEvent?:boolean;onReady:()=>void;onBack:()=>void}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const [vault]=useState(()=>new DeviceVault());const [records,setRecords]=useState<RecoveryMetadata[]>([]);const [discovery,setDiscovery]=useState<'loading'|'ready'|'failed'>('loading');const [recordId,setRecordId]=useState('');const [password,setPassword]=useState('');const [confirmation,setConfirmation]=useState('');const [remember,setRemember]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [backup,setBackup]=useState<RecoveryMetadata>();const [newId,setNewId]=useState(()=>newEvent?hexFromBytes(crypto.getRandomValues(new Uint8Array(32))):'');
  const lifecycle=useRef<AbortController>(new AbortController());
  useEffect(()=>{const current=new AbortController();lifecycle.current=current;return()=>{current.abort();controller.consent.respond(false)}},[controller]);
  function approvalScope(){const current=lifecycle.current;const guard=controller.ownerControlGuard();return {isCurrent:()=>!current.signal.aborted&&guard(),signal:AbortSignal.any([current.signal,controller.ownerControlSignal()])}}
  const eventId=newEvent?newId:view.event?.eventId??'';const active=records.find(r=>vaultScopeKey(r)===recordId)??records[0];const locked=busy||view.busy||!view.loaded||discovery==='loading';
  useEffect(()=>{let valid=true;setDiscovery('loading');void vault.list().then(rows=>{if(valid){setRecords(rows.filter(r=>r.role===role&&(!eventId||r.eventId===eventId)));setDiscovery('ready')}}).catch(()=>{if(valid){setDiscovery('failed');setError('Saved device access could not be read. Keep site data and restore your existing backup; do not create replacement organiser authority.')}});return()=>{valid=false;setPassword('');setConfirmation('')}},[vault,role,eventId]);
  function clear(){setPassword('');setConfirmation('');setBusy(false)}
  async function unlock(){if(!active||busy)return;const {isCurrent,signal}=approvalScope();setBusy(true);setError('');try{
    if(!await controller.consent.request({requirement:'importPrivateFile',title:'Unlock your saved access?',acceptLabel:'Unlock my encrypted device access',details:[`Role: ${active.role} · event: ${active.eventId} · local account: ${active.ownerAccountId}`,'Your password is used only in this browser to decrypt existing authority. Nothing is uploaded, regenerated or replaced.','Keep a recovery backup. This browser storage cannot be recovered if both it and all backups are lost.']})||!isCurrent())return;
    const custody=await vault.unlock(active,password,{ownerApproved:true,isCurrent,signal});if(!isCurrent()){forgetCustody(custody);return}controller.setCustody(custody);setBackup(active);if(role==='bearer')controller.prepareBearerCommitment();onReady();
  }catch{setError('Could not unlock. Check your password and selected event. Your existing access was not changed or replaced.')}finally{clear()}}
  async function provision(){if(busy||discovery!=='ready'||records.length)return;const {isCurrent,signal}=approvalScope();setBusy(true);setError('');try{
    publicHex32(eventId);validateVaultPassword(password);if(password!==confirmation)throw new Error('Passwords do not match');const account=`device-${crypto.randomUUID()}`;
    if(!await controller.consent.request({requirement:'provision',title:role==='issuer'?'Create authority for a separate new event?':'Set up your own private pass?',acceptLabel:role==='issuer'?'I create this new event authority':'I create and save my private pass',details:[`Role: ${role} · Preview event: ${eventId}`,'Creates a new private capability and a new random encryption key on this device. You personally control this action.','The existing authority is encrypted with your password and saved in this browser. No plaintext key or password is stored, downloaded, copied or sent to the organiser.','Use a unique password of at least 15 characters. Same-origin malicious code can still access secrets while unlocked; this is not biometric or hardware-backed protection.',role==='issuer'?'This creates new issuer and maintenance authority, never a replacement for the recorded event. Losing all copies permanently prevents further issue/revoke.':'Only you receive the bearer capability. The organiser receives a public commitment.', 'Encrypted recovery backup is optional after setup. Browser storage is not a backup; site-data clearing or device loss can erase it. No wallet or transaction is requested here.']})||!isCurrent())return;
    const file=await createRecoveryFile({role,eventId,ownerAccountId:account,includeMaintenance:newEvent&&role==='issuer',ownerConfirmedFinalAction:true,createMaintenanceKey:()=>controller.sdk().ownerCreateMaintenanceSigningKey({ownerConfirmedFinalAction:true,role:'issuer'})});
    if(!isCurrent())return;const text=JSON.stringify(file);const scope={role,eventId,ownerAccountId:account};await vault.remember(text,scope,password,{ownerApproved:true,isCurrent,signal});const custody=await importOwnerFile(text,scope);if(!isCurrent()){forgetCustody(custody);return}controller.setCustody(custody);setBackup({...scope,network:'preview'});if(role==='bearer')controller.prepareBearerCommitment();
  }catch(e){setError(e instanceof Error&&e.message==='Passwords do not match'?'Passwords do not match.': 'Setup could not finish. Use a unique password of 15–128 characters, keep any existing saved access, and try unlocking or restoring it before creating again.')}finally{clear()}}
  async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(!file||busy)return;const {isCurrent,signal}=approvalScope();setBusy(true);setError('');try{
    if(file.size>16384)throw new Error();const text=await file.text();if(!isCurrent())return;let encrypted=false;let metadata:RecoveryMetadata;try{metadata=readEncryptedBackupMetadata(text,role);encrypted=true}catch{metadata=readOwnerRecoveryMetadata(text,role)}
    const scope=resolveRecoveryScope(metadata,{role,eventId,ownerAccountId:''});if(remember&&!encrypted)validateVaultPassword(password);
    if(!await controller.consent.request({requirement:'importPrivateFile',title:'Restore your existing private access?',acceptLabel:'I unlock my local recovery file',details:[`Role: ${scope.role} · event: ${scope.eventId} · original local account: ${scope.ownerAccountId}`,'The exact existing owner/event/role namespace and authority are preserved. No private file or key is uploaded. No new authority is generated.',encrypted?'This encrypted backup is unlocked with its original password and saved add-only on this device.':remember?'Your existing recovery authority is encrypted with the password you entered and saved on this device for future unlocks.':'This recovery authority is unlocked in memory for this visit only.','Private storage and wallet/prover connection are separate from network approval. Keep your existing backup secure.']})||!isCurrent())return;
    let custody;if(encrypted)custody=await vault.importBackup(text,scope,password,{ownerApproved:true,isCurrent,signal});else{if(remember)await vault.remember(text,scope,password,{ownerApproved:true,isCurrent,signal});custody=await importOwnerFile(text,scope)}
    if(!isCurrent()){forgetCustody(custody);return}controller.setCustody(custody);if(encrypted||remember)setBackup(scope);if(role==='bearer')controller.prepareBearerCommitment();onReady();
  }catch{setError('Recovery was rejected. Check the password, role and exact event. Existing device access was not overwritten. Keep your original recovery file and site data.')}finally{clear()}}
  const savedBackup=backup??records.find(r=>{const scope=controller.custodyScope;return scope&&vaultScopeKey(r)===vaultScopeKey(scope)});
  async function exportBackup(){if(!savedBackup)return;try{const text=await vault.exportBackup(savedBackup);downloadEncryptedBackup(text,role);setError('Encrypted backup downloaded. Keep it offline with a separate record of your password; never share either with the organiser or gate.')}catch{setError('Backup could not be prepared. Keep this device’s access and do not clear site data.')}}
  return <section className="journey-card live-panel"><StepTitle eyebrow={newEvent?'Separate new event':'02 · Your access'} title={view.custodyReady?'Your access is unlocked':active?'Welcome back':role==='issuer'&&!newEvent?'Unlock organiser access':'Set up your private pass'} text={role==='issuer'&&!newEvent?'Restore the original issuer for this event. A new issuer cannot recover it.':'Your private capability stays on this device. The public pass code contains no secret.'}/>{role==='bearer'&&<p className="requirement-note"><Cable size={18}/><span>Request a pass now without a wallet. Real check-in later requires Lace 2.4.2 on Preview, the compatible local prover 8.1.0 at localhost:6300, test DUST and your transaction approval.</span></p>}
    {discovery==='loading'&&<p role="status" className="live-small-note">Checking for existing saved access…</p>}{view.custodyReady?<><p className="live-good"><LockKeyhole size={18}/>{role==='issuer'?'Organiser':'Guest'} access unlocked for this visit</p><button className="button primary" onClick={onReady}>{role==='bearer'?'Show my pass request':'Continue to wallet'}<ArrowRight size={17}/></button>{savedBackup&&<details className="technical-note"><summary>Save an optional encrypted recovery backup</summary><p>Browser storage can be lost. A backup plus its password restores the same authority on another device. Without either, the pass or organiser access may be lost permanently.</p><button className="button secondary" onClick={()=>void exportBackup()}><Download size={16}/>Download encrypted recovery backup</button></details>}</>:<>{newEvent&&<label className="form-field">New public event ID<input aria-label="New public event ID" className="mono" value={newId} disabled={locked} onChange={e=>setNewId(e.target.value)}/><small>A distinct event is deliberate. Keep the recorded deployment for existing passes.</small></label>}{active&&<label className="form-field">Saved access<select aria-label="Saved device access" value={recordId||vaultScopeKey(active)} disabled={locked} onChange={e=>setRecordId(e.target.value)}>{records.map(r=><option key={vaultScopeKey(r)} value={vaultScopeKey(r)}>{r.ownerAccountId} · {r.role}</option>)}</select></label>}
    <label className="form-field">{active?'Device password':'Device or encrypted-backup password'}<input type="password" aria-label="Device password" autoComplete={active?'current-password':'new-password'} value={password} disabled={locked} maxLength={128} onChange={e=>setPassword(e.target.value)}/><small>{active?'Unlocks the same saved authority. It never creates a new pass.':'Use 15–128 characters for new device storage, or the original password for an encrypted backup.'}</small></label>
    {active?<button className="button primary" disabled={locked||!password} onClick={()=>void unlock()}><KeyRound size={18}/>Unlock {role==='issuer'?'organiser access':'my pass'}</button>:role==='bearer'||newEvent?<><label className="form-field">Repeat new device password<input type="password" aria-label="Confirm device password" autoComplete="new-password" disabled={locked} value={confirmation} maxLength={128} onChange={e=>setConfirmation(e.target.value)}/></label><button className="button primary" disabled={locked||discovery!=='ready'||password.length<15||password!==confirmation||!eventId} onClick={()=>void provision()}><LockKeyhole size={18}/>{newEvent?'Create separate event authority':'Set up my pass'}</button></>:<p className="live-small-note">Choose your existing recovery file below. No replacement issuer will be generated if unlock fails.</p>}
    <details className="technical-note" open={!active&&role==='issuer'&&!newEvent}><summary>Restore existing access from a recovery file</summary><p>Use the original issuer or your own bearer file. Choose it directly; there’s no need to open or paste private JSON.</p>{!active&&<label className="live-checkbox"><input type="checkbox" checked={remember} disabled={locked} onChange={e=>setRemember(e.target.checked)}/>Remember an older unencrypted recovery file securely on this device</label>}<label className="live-file-picker">Choose your own existing recovery file<input type="file" aria-label="Choose owner private recovery file" accept="application/json,.json" disabled={locked} onChange={importFile}/></label></details></>}{error&&<p role="status" className="live-small-note">{error}</p>}{busy&&<p role="status"><LoaderCircle className="spin" size={16}/> Protecting your access…</p>}<Back onClick={onBack}/></section>;
}
function WalletStep({controller,onReady,onBack}:{controller:LiveController;onReady:()=>void;onBack:()=>void}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const [wallets,setWallets]=useState<Array<{id:string;api:WalletApi}>>([]);const [walletId,setWalletId]=useState('');const [prover,setProver]=useState('');
  function refresh(){const found=controller.wallets();setWallets(found);const compatible=found.filter(w=>/^4\./.test(w.api.apiVersion));if(compatible.length===1)setWalletId(compatible[0].id)}
  useEffect(()=>{if(view.loaded)refresh()},[view.loaded]);
  async function connect(){if(view.busy)return;const selected=wallets.find(w=>w.id===walletId);if(!view.connected){if(!selected)return;await controller.connect(selected.api,prover)}if(!controller.getSnapshot().connected||controller.getSnapshot().error)return;await controller.readNetwork();const next=controller.getSnapshot();if(next.error||!next.chain)return;if(next.event){if(!next.joined)await controller.join(publicManifest(next.event));if(controller.getSnapshot().joined)onReady()}}
  return <section className="journey-card live-panel"><StepTitle eyebrow="Preview connection" title={view.joined?'You’re ready for a transaction':'Connect when you’re ready'} text="Lace asks for the wallet permissions and transaction approvals it needs. Your local prover handles private witness data."/><ol className="readiness-list"><li>Chrome with Lace 2.4.2, switched to Midnight Preview</li><li>Compatible local proof server 8.1.0 at localhost:6300</li><li>Preview test funding and enough DUST for the transaction</li></ol><div className="live-fields"><label className="form-field">Wallet<select aria-label="Selected live wallet" value={walletId} disabled={view.busy||view.connected} onChange={e=>setWalletId(e.target.value)}><option value="">Choose a compatible wallet</option>{wallets.map(w=><option key={w.id} value={w.id} disabled={!/^4\./.test(w.api.apiVersion)}>{w.api.name} · API {w.api.apiVersion}</option>)}</select></label>{!wallets.length&&<p className="requirement-note">No wallet is available in this browser. Open this event on your own Chrome/Lace browser. Your request and event can stay saved here.</p>}<button className="text-button" disabled={view.busy} onClick={refresh}>Refresh available wallets</button><label className="form-field">Confirm the local prover you configured<input aria-label="Owner local prover destination" value={prover} disabled={view.busy||view.connected} onChange={e=>setProver(e.target.value)} placeholder="http://localhost:6300"/><small>This is your review of Lace’s actual setting. Typing a value does not install or independently verify the prover.</small></label>{!view.joined&&!(view.connected&&!view.event&&view.chain)?<button className="button primary" disabled={view.busy||!view.custodyReady||(!view.connected&&(!walletId||!prover.trim()))} onClick={()=>void connect()}><Cable size={18}/>{view.connected?'Verify this event':'Connect Preview'}</button>:view.joined?<button className="button primary" onClick={onReady}>Continue<ArrowRight size={17}/></button>:null}{view.connected&&!view.event&&view.chain&&<><p className="live-small-note">This is a new event. Review the deployment separately. Never redeploy an unresolved request.</p><button className="button primary" disabled={view.busy||view.attempts.some(isUnresolved)} onClick={()=>void controller.deploy().then(()=>{if(controller.getSnapshot().joined)onReady()})}>Review new Preview deployment</button></>}{view.chain&&<p className="live-good"><Check size={17}/>Finalized node head read at block {view.chain.finalizedBlockHeight}</p>}</div><Back onClick={onBack}/></section>;
}
function IssueStep({controller}:{controller:LiveController}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const [commitment,setCommitment]=useState('');const [error,setError]=useState('');const [review,setReview]=useState(false);const [revoke,setRevoke]=useState(false);
  const scope=controller.custodyScope;const last=view.attempts.filter(a=>a.action==='issue'&&a.role==='issuer'&&a.ownerAccountId===scope?.ownerAccountId&&a.eventId===view.event?.eventId&&a.commitment===commitment&&a.status==='verified'&&a.receipt?.contractAddress===view.event?.contractAddress&&a.receipt?.publicState.issuerCommitment===view.event?.issuerCommitment).at(-1);
  function accept(text:string){try{const request=parsePassRequest(text,publicManifest(view.event!));setCommitment(request.commitment);setReview(true);setError('')}catch{setError('This request does not match the trusted event, or is not a public pass request. No pass was issued.')}}
  return <section className="journey-card live-panel"><StepTitle eyebrow="Organiser · guest requests" title={last?'Pass issued':review?'Review this guest request':'Approve a guest’s request'} text={last?'The issue transaction is finalized and independently verified. The guest can refresh their pass status.':'The guest creates their own private pass. You receive only their public commitment.'}/>{last?<><LastReceipt attempts={[last]}/><button className="button primary" onClick={()=>{setCommitment('');setReview(false)}}>Issue another pass<Plus size={17}/></button></>:review?<><div className="request-summary"><Check size={20}/><div><strong>Request matches this event</strong><p className="mono break-word">{commitment}</p></div></div><button className="button primary" disabled={view.busy||!view.joined} onClick={()=>void controller.issue(commitment)}>Issue pass<ArrowRight size={17}/></button><button className="text-button" disabled={view.busy} onClick={()=>{setReview(false);setCommitment('')}}>Choose another request</button></>:<PublicCodeInput label="guest request" onCode={accept} disabled={view.busy}/>}{error&&<p role="alert" className="form-error">{error}</p>}<details className="technical-note"><summary>Advanced: public commitment & revocation</summary><label className="form-field">Public commitment<input aria-label="Live issue commitment" className="mono" value={commitment} onChange={e=>{setCommitment(e.target.value);setReview(false);setRevoke(false)}}/></label><button className="button secondary" disabled={view.busy||!commitment} onClick={()=>{try{publicHex32(commitment);setReview(true);setError('')}catch{setError('Enter a valid public commitment')}}}>Review pass</button><button className="text-button danger-text" disabled={view.busy||!commitment} onClick={()=>setRevoke(true)}>Revoke this commitment…</button>{revoke&&<div className="revoke-warning"><p>Revocation is permanent for this commitment. Review the exact event and pass in the next approval.</p><button className="button secondary" disabled={view.busy} onClick={()=>void controller.revoke(commitment)}>Review revocation</button><button className="text-button" onClick={()=>setRevoke(false)}>Keep pass</button></div>}</details></section>;
}
function GuestPass({controller,onDoor}:{controller:LiveController;onDoor:()=>void}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const started=useRef(false);
  useEffect(()=>{if(!view.commitment)controller.prepareBearerCommitment();if(!started.current){started.current=true;const current=controller.getSnapshot();if(current.commitment&&current.event)void controller.readPublicEvent(current.commitment)}},[controller,view.commitment]);
  const active=view.publicVerified&&view.state?.passStatus==='ACTIVE';const terminal=view.state?.passStatus==='USED'||view.state?.passStatus==='REVOKED';
  return <section className="journey-card live-panel guest-pass-step"><StepTitle eyebrow="Guest · my pass" title={active?'Your pass is active':terminal?view.state?.passStatus==='USED'?'This pass has been used':'This pass is revoked':'Your pass request is ready'} text={active?'At the door, show this public code. Your private bearer capability stays on your device.':terminal?'A used or revoked pass cannot grant another entry. Contact the organiser if you need help.':'Show this public request to the organiser. It contains no bearer secret.'}/>{view.event&&view.commitment&&<PublicQr value={active?encodeCheckInRequest(publicManifest(view.event),view.commitment):encodePassRequest(publicManifest(view.event),view.commitment)} label={active?'Public pass check-in QR':'Public pass request QR'}/>}<p className={`pass-state ${active?'pass-state-active':''}`} role="status">{view.busy?'Checking public status…':active?'ACTIVE · independently checked':terminal?view.state?.passStatus:view.publicVerified?'Waiting for organiser approval':'Request prepared · current status not verified'}</p>{active?<button className="button primary" onClick={onDoor}>Check in at the door<ArrowRight size={17}/></button>:<button className="button primary" disabled={view.busy||!view.commitment} onClick={()=>void controller.readPublicEvent(view.commitment)}>Refresh pass status</button>}{active&&<button className="text-button" disabled={view.busy} onClick={()=>void controller.readPublicEvent(view.commitment)}>Refresh public status</button>}<p className="live-small-note">Real check-in requires your own Lace Preview wallet, compatible local prover and transaction approval. ACTIVE is pass status; only the gate can confirm admission.</p><details className="technical-note"><summary>Public details</summary><p className="mono break-word">{view.commitment}</p><p>{view.publicCheckedAt?`Latest indexed status checked ${new Date(view.publicCheckedAt).toLocaleTimeString()}. This is not a finalized gate baseline.`:'No current independent pass status available.'}</p></details></section>;
}
function GuestDoor({controller,onWallet,onBack}:{controller:LiveController;onWallet:()=>void;onBack:()=>void}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const [request,setRequest]=useState<PublicGateRequest>();const [error,setError]=useState('');const [now,setNow]=useState(Date.now());const recordKey=`guestlist.midnight-preview.guest-request.${view.event?.contractAddress}.${view.commitment}`;
  useEffect(()=>{if(!view.event||!view.commitment)return;try{const text=localStorage.getItem(recordKey);if(text)setRequest(parsePreservedGateRequest(text,publicManifest(view.event),view.commitment))}catch{/* A stale request is never restored as current authorization. */}},[recordKey]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
  function accept(text:string){try{if(!view.event||!view.commitment)throw new Error();const value=parseGateRequest(text,publicManifest(view.event),view.commitment);localStorage.setItem(`${recordKey}.${value.requestId}`,JSON.stringify(value));localStorage.setItem(recordKey,JSON.stringify(value));setRequest(value);setError('')}catch{setError('This gate request is expired or does not match your pass and trusted event. Ask the gate for a current request.')}}
  const redemption=request?view.attempts.filter(a=>a.action==='redeem'&&a.requestId===request.requestId&&a.status==='verified'&&a.commitment===request.commitment&&a.ownerAccountId===controller.custodyScope?.ownerAccountId&&a.role==='bearer'&&a.eventId===request.eventId&&a.receipt?.contractAddress===request.contractAddress&&a.receipt?.publicState.issuerCommitment===request.issuerCommitment).at(-1):undefined;
  let receiptCode='';try{if(request&&redemption?.receipt)receiptCode=encodeRedemptionReceipt(request,redemption.receipt)}catch{/* Invalid binding never yields a receipt QR. */}
  const expired=!!request&&request.expiresAt<=now;
  async function redeem(){try{if(!request||!view.event||!view.commitment)throw new Error();parseGateRequest(JSON.stringify(request),publicManifest(view.event),view.commitment);await controller.redeemGateRequest(request)}catch{setError('The request is no longer valid. No new redemption was started. Ask the gate for the next safe step.')}}
  return <section className="journey-card live-panel"><StepTitle eyebrow="Guest · check-in" title={receiptCode?'Redemption confirmed':request?'Approve your check-in':'Scan the gate’s request'} text={receiptCode?'Show this public receipt to gate staff. Wait for their independent admission decision.':'First show your public pass code to the gate. They return a request bound to this event and your pass.'}/>{receiptCode?<><PublicQr value={receiptCode} label="Public finalized redemption receipt QR"/><p className="live-good"><Check size={18}/>Finalized redemption verified · waiting for gate</p><p className="live-small-note">This screen does not say Admitted. The gate must independently verify and claim this exact request once.</p></>:request?<><div className="request-summary"><ShieldCheck size={22}/><div><strong>{expired?'Gate request expired':'Request matches your pass'}</strong><p>{expired?'Ask the gate to resolve this attempt before doing anything else.':`Expires in ${Math.max(0,Math.ceil((request.expiresAt-now)/1000))} seconds`}</p></div></div>{!view.joined?<><p className="live-small-note">Connect your own Preview wallet and local prover before approving redemption.</p><button className="button primary" disabled={expired} onClick={onWallet}>Connect for check-in<ArrowRight size={17}/></button></>:<button className="button primary" disabled={view.busy||expired||view.attempts.some(a=>a.requestId===request.requestId&&isUnresolved(a))} onClick={()=>void redeem()}>Approve check-in<ArrowRight size={17}/></button>}<button className="text-button" disabled={view.busy||view.attempts.some(a=>a.requestId===request.requestId&&isUnresolved(a))} onClick={()=>{setRequest(undefined);localStorage.removeItem(recordKey)}}>Scan a different request</button><details className="technical-note"><summary>Public gate request</summary><p className="mono break-word">{request.requestId}</p><p>ACTIVE baseline block {request.baselineBlockHeight}. A public code can be altered; only your trusted physical gate supplies this request. The backend makes the admission decision.</p></details></>:<><PublicCodeInput label="gate request" onCode={accept} disabled={view.busy}/>{view.event&&view.commitment&&<details className="technical-note"><summary>Show my public pass code</summary><PublicQr value={encodeCheckInRequest(publicManifest(view.event),view.commitment)} label="Public pass check-in QR"/></details>}</>}{error&&<p className="form-error" role="alert">{error}</p>}<Back onClick={onBack}/></section>;
}
function GateFlow({controller}:{controller:LiveController}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const [commitment,setCommitment]=useState('');const [receipt,setReceipt]=useState<{requestId:string;txId:string}>();const [error,setError]=useState('');const [showNext,setShowNext]=useState(false);const context=view.gateContext;const txId=receipt?.requestId===context?.requestId?receipt?.txId??'':context?.status==='open'?context.txId??'':'';const pending=context&&context.status!=='closed';let code='';try{if(context)code=encodeGateRequest(gatePublic(context))}catch{}
  useEffect(()=>()=>controller.dismissAdmission(),[controller]);
  function scanPass(text:string){try{if(!view.event)throw new Error();const value=parseCheckInRequest(text,publicManifest(view.event));setCommitment(value.commitment);setReceipt(undefined);setError('');setShowNext(true)}catch{setError('This is not a public check-in code for the trusted event. No gate attempt was opened.')}}
  function scanReceipt(text:string){try{if(!context)throw new Error();const value=parseRedemptionReceipt(text,gatePublic(context));setReceipt({requestId:context.requestId,txId:value.txId});setError('')}catch{setError('Receipt does not match this gate request, event and pass. Entry remains closed.')}}
  const admitted=view.admission?.admit===true&&!showNext;
  return <section className="journey-card live-panel"><StepTitle eyebrow="Gate staff · door" title={admitted?'Admitted':pending?txId?'Verify this entry':'Waiting for the guest':'Scan the next pass'} text={admitted?'The first durable claim was verified for this request.':pending?'The guest approves on their own device. Only a verified first claim opens entry.':'Ask the guest to show their public check-in QR. No private credential belongs on this device.'}/>{admitted?<><div className="gate-result result-success" role="status"><ShieldCheck size={42}/><h2>Admitted</h2><p>Independent finalized verification · first durable claim</p></div><button className="button primary" onClick={()=>{controller.dismissAdmission();setShowNext(true);setCommitment('');setReceipt(undefined)}}>Next guest<ArrowRight size={17}/></button></>:pending?<>{code&&<><PublicQr value={code} label="Public gate request QR"/><p className="live-small-note">Guest scans this request, then returns a public finalized receipt QR. Gate authentication stays on this device.</p></>}{context.status==='open'?<>{!txId?<PublicCodeInput label="guest receipt" onCode={scanReceipt} disabled={view.busy}/>:<><p className="live-good"><Check size={18}/>Public receipt matches the open request</p><button className="button primary" disabled={view.busy} onClick={()=>void controller.claimGate(context.requestId,txId)}>Verify admission<ShieldCheck size={17}/></button>{!context.txId&&<button className="text-button" onClick={()=>setReceipt(undefined)}>Scan another receipt</button>}</>}</>:<p className="requirement-note">The previous request is {context.status}. Check its saved status. Do not start another redemption or assume entry was granted.</p>}<button className="button secondary" disabled={view.busy} onClick={()=>void controller.readGate(context.requestId)}>Check existing gate status</button><details className="technical-note"><summary>Preserved public request</summary><p className="mono break-word">{context.requestId}</p><p>{context.status} · ACTIVE baseline {context.baselineBlockHeight??'not yet verified'}</p></details></>:<>{commitment?<><p className="live-good"><Check size={18}/>Public pass matches this event</p><button className="button primary" disabled={view.busy} onClick={()=>{setShowNext(false);void controller.openGate(commitment)}}>Start check-in<ArrowRight size={17}/></button><button className="text-button" onClick={()=>setCommitment('')}>Scan a different pass</button></>:<PublicCodeInput label="guest pass" onCode={scanPass} disabled={view.busy}/>}<p className="live-small-note">The gate first verifies ACTIVE and records the baseline. A used pass or replay cannot start a new entry.</p>{view.admission&&!admitted&&<p role="status" className="requirement-note">Entry closed · {view.admission.code}. A status read never admits again.</p>}</>}{error&&<p className="form-error" role="alert">{error}</p>}</section>;
}
function ConsentDialog({ queue }: { queue: ConsentQueue }) {
  const request = useSyncExternalStore(queue.subscribe, queue.getSnapshot, queue.getSnapshot);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    const node = dialog.current; if (!node || !request) return;
    const previous = document.activeElement;
    if (!node.open) node.showModal();
    return () => { if (node.open) node.close(); if (previous instanceof HTMLElement && previous.isConnected) previous.focus(); };
  }, [request]);
  if (!request) return null;
  const rule = CONSENT_REQUIREMENTS[request.requirement];
  return <dialog ref={dialog} className="dialog live-consent" aria-labelledby="live-consent-title" data-consent-requirement={request.requirement} data-owner-final-action={rule.ownerFinalAction} onCancel={event => { event.preventDefault(); queue.respond(false); }}>
    <div className="dialog-head"><div><h2 id="live-consent-title">{request.title}</h2><p>Owner review · {rule.mode}</p></div><button className="icon-button" aria-label="Decline and close owner review" onClick={() => queue.respond(false)}><X size={20}/></button></div>
    <div className="dialog-body"><ul className="live-review-list">{request.details.map((detail, index) => <li key={index}>{detail}</li>)}</ul><p className="live-owner-control">Only the owner should operate the final approval. An assistant must not create/import private authority or accept this review for you.</p></div>
    <div className="dialog-actions"><button autoFocus className="button secondary" onClick={() => queue.respond(false)}>Decline</button><button className="button primary" onClick={() => queue.respond(true)}>{request.acceptLabel}</button></div>
  </dialog>;
}
function GateSetup({controller}:{controller:LiveController}) {
  const mount=useRef({active:true,client:undefined as ReturnType<typeof createAdmissionClient>|undefined});
  useEffect(()=>{const current={active:true,client:undefined as ReturnType<typeof createAdmissionClient>|undefined};mount.current=current;return()=>{current.active=false;current.client?.close();controller.consent.respond(false);if(controller.getSnapshot().busy)controller.disconnect()}},[controller]);
  const view = useSyncExternalStore(controller.subscribe, controller.getSnapshot, controller.getSnapshot); const [error, setError] = useState('');
  async function selected(event:ChangeEvent<HTMLInputElement>) {
    const input = event.currentTarget, file = input.files?.[0]; input.value = ''; if (!file) return; setError('');
    const current=mount.current, guard=controller.ownerControlGuard();const stillOwner=()=>current.active&&guard();
    let client: ReturnType<typeof createAdmissionClient> | undefined;
    try {
      if (file.size > 8192 || !view.event) throw new Error('Trusted event needed');
      const raw: unknown = JSON.parse(await file.text());
      if (!stillOwner()) return;
      if (!raw || typeof raw !== 'object') throw new Error('Invalid owner file');
      const v = raw as Record<string,unknown>;
      if (Object.keys(v).some(k => !['schema','serviceUrl','gateId','apiSecret'].includes(k)) || v.schema !== 'guestlist-gate-client-v1' || typeof v.serviceUrl !== 'string' || typeof v.gateId !== 'string' || typeof v.apiSecret !== 'string') throw new Error('Invalid gate file');
      const service = new URL(v.serviceUrl);
      if (service.username || service.password || service.search || service.hash || !['http:','https:'].includes(service.protocol) || !['localhost','127.0.0.1','[::1]'].includes(service.hostname) && service.protocol !== 'https:') throw new Error('Invalid gate service');
      if (!await controller.consent.request({ requirement:'gateAuthority', title:'Personally connect existing gate authority?', acceptLabel:'I take control: authorize this gate service', details:[`Service receiving authentication authority: ${service.href}`,`Gate ID: ${v.gateId}`,`Preview contract: ${view.event.contractAddress}`, 'This imports an existing owner-provisioned API secret from your local file and transmits it only as authentication to this exact approved gate service.', 'No authority is created or enlarged. The secret remains in memory and is discarded on Lock or mode exit; it never enters localStorage, a URL, a public bundle, an issuer vault or a bearer credential.', 'All physical gates must use this same durable configured backend. A browser journal alone cannot coordinate entry.'] })) return;
      if (!stillOwner()) return; client = createAdmissionClient({serviceUrl:v.serviceUrl,gateId:v.gateId,apiSecret:v.apiSecret});current.client=client;
      await controller.setGate(client);if(!stillOwner()){client.close();return}current.client=undefined; client = undefined;
    } catch { client?.close(); setError('Gate setup rejected. Review the trusted event and exact owner-provisioned gate service file. No admission is granted.'); }
  }
  return <div className="live-fields"><label className="live-file-picker">Personally choose existing gate connection file<input aria-label="Choose owner gate authority file" type="file" accept="application/json,.json" disabled={view.busy || !view.event} onChange={selected}/></label><small>Backend setup creates this owner-held file through its separate reviewed provisioning procedure. Do not paste the API secret into chat.</small>{error && <p role="alert" className="live-small-note">{error}</p>}</div>;
}
function LastReceipt({attempts}:{attempts:PublicAttempt[]}){const last=attempts.filter(a=>a.status==='verified').at(-1);if(!last?.receipt)return <p className="live-small-note">No attributed finalized receipt has been verified in this browser yet</p>;const receipt=last.receipt;return <div className="live-evidence"><strong>{receipt.action} · finalized and independently verified</strong><p>Block {receipt.blockHeight} · {receipt.publicState.passStatus??'deployment'}</p><p className="mono break-word">Transaction {receipt.txId}</p><p className="mono break-word">Block {receipt.blockHash}</p><small>Request {last.requestId} is a correlation ID, not a transaction ID</small></div>}
function Requests({controller,copyPublic}:{controller:LiveController;copyPublic:(v:string)=>Promise<void>}){
  const view=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot);const [address,setAddress]=useState('');
  return <section className="live-panel"><div className="section-heading"><div><h2>Public requests & receipts</h2><p>Pending/unknown requests are reconciled read-only. They are never automatically resubmitted.</p></div></div>{view.attempts.length===0?<p>No network operation has been started</p>:<div className="live-request-list">{view.attempts.slice().reverse().map(attempt=><article key={attempt.requestId}><div className="live-request-heading"><strong>{attempt.action} · {attempt.status}</strong><span className="role-label">{attempt.role}</span></div><p className="mono break-word">Request: {attempt.requestId}</p>{attempt.commitment&&<p className="mono break-word">Commitment: {attempt.commitment}</p>}{attempt.receipt&&<><p className="mono break-word">Actual tx: {attempt.receipt.txId}</p><p>Finalized block {attempt.receipt.blockHeight} · independent state {attempt.receipt.publicState.passStatus??'deployment'}</p><button className="text-button" onClick={()=>void copyPublic(JSON.stringify(attempt.receipt))}><Copy size={15}/>Copy public receipt</button></>}{isUnresolved(attempt)&&<><p className="live-small-note">Keep this exact owner/event/role and request ID. No success or entry is inferred.</p>{attempt.action==='deploy'&&<label className="form-field">Recovered public deployment address (optional)<input className="mono" value={address} onChange={e=>setAddress(e.target.value)}/></label>}<button className="button secondary" disabled={view.busy||!view.connected} onClick={()=>void controller.reconcile(attempt.requestId,attempt.action==='deploy'?address.trim():undefined)}>Reconcile this request only</button></>}</article>)}</div>}</section>;
}
